### ISSUE TITLE
Removing attachments is broken

### ISSUE THREAD

**Issue by luontola** [CSCfi/rems#1028]
1. Add an attachment to an application
2. Remove the attachment
3. Reload the page

Expected: there is no attachment

Actual: the attachment's name is still there, but the link is broken

**Comment by opqdonut** [comment]
can't reproduce with a fresh application on master. the draft generated by `lein run test-data` does work a bit weirdly though

**Comment by opqdonut** [comment]
no wait there is something going on if you don't press Save after removing an attachment
