### ISSUE TITLE
Only use license table expiration

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#1116]
We have start and end dates for resource and workflow licenses stored separately and in the common license table. We should have only one place for the, i.e. the common table.

Now a license can be expired in the resource licenses sense but not in the general license sense. And the API will happily return it when you get all licenses.

- [ ] only have start and end dates in licenses table
- [ ] migration for old db
- [ ] test for this case of expiration in the API

**Comment by opqdonut** [comment]
Should we have any expiration for licenses?
