### ISSUE TITLE
Prefer eagerly storing vecs into application view

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#1118]
Prefer storing data into application view by eagerly computing vectors.

I.e. more this

```
             :application/resources (mapv #(select-keys % [:catalogue-item/id :resource/ext-id])
                                         (:application/resources event))
```

And less this

```
             :application/resources (map #(select-keys % [:catalogue-item/id :resource/ext-id])
                                         (:application/resources event))
```

**Comment by luontola** [comment]
It would be possible to write a test which will dig through the whole application data structure and report any places where a `clojure.lang.LazySeq` was found.

**Comment by opqdonut** [comment]
Probably mostly done, but the test is a nice idea.

**Comment by opqdonut** [comment]
idea split out
