### ISSUE TITLE
LBR: Different application numbering for different REMS instances

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#1133]
- [x] make it possible to configure which ID numbering is used (old: number, new: number within year + description)
- [ ] configure LBR to use old and THL to use new

It seems that the application numbers have changed from simple running numbers to year/number. This may be more human-readable now, but it may also make it difficult to refer to past applications by number (for example by external parties who have received application data in pdf format from us).

**Comment by jaakkocsc** [comment]
It would probably be most convenient to follow diaarinumero convention: running number, diaarikaavan ryhmätunnus (no idea about english translation for that) and year; e.g. 44/24/2019. Or, it might even be reasonable to separate rems internal id number from user representation (this would naturally cause code & db changes)?

**Comment by opqdonut** [comment]
Currently the internal id (example: 13) is separate from the user representation (example: 2019/04)

**Comment by okahilak** [comment]
"configure LBR to use old and THL to use new" is still to be done. Moving back to backlog.
