### ISSUE TITLE
LBR: Release notes for the next release

### ISSUE THREAD

**Issue by luontola** [CSCfi/rems#1165]
The next release has big changes due to the replacement of old workflows with dynamic workflow. Upgrade instructions are needed. You may write a draft of the release notes to this issue.

----

Draft:

# Upgrading

1. Migrate the database with `lein run migrate`
2. Go to the administration pages, create a new dynamic workflow and take note of its ID for the next step
3. Run `lein run convert-to-dynamic <id>` where `<id>` is the workflow ID from the previous step. This will convert all applications and catalogue items to use that new workflow
4. Go to the administration pages and archive all non-dynamic workflows

**Comment by opqdonut** [comment]
See #1475 for conversion instructions
