### ISSUE TITLE
LBR: Applications table layout breaks when userid is too long

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#1174]
The View button is rendered outside the visible area.

Example:

![application-table-wide](https://user-images.githubusercontent.com/207385/56897284-c4266500-6a96-11e9-8e4f-468eb386b06e.png)

See also #1230

**Comment by luontola** [comment]
Probably related to #1179

**Comment by opqdonut** [comment]
now it looks like this:

![wide-applications-table](https://user-images.githubusercontent.com/207385/57354371-f52c2700-7173-11e9-9b74-574a0f80e3ca.png)

**Comment by opqdonut** [comment]
misclosed
