### ISSUE TITLE
LBR: Embed Shibboleth EDS to the login page

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1255]
Currently (in their production service) the login page only shows Haka-login and EDS is provided by a separate link below Haka. The EDS should be directly under Haka option. THL has this option already in their REMS1 production instance (https://thl-biobank.elixir-finland.org/login)

**Comment by opqdonut** [comment]
These seem to be the relevant instructions: https://wiki.eduuni.fi/display/CSCHAKA/Embedded+DS

**Comment by opqdonut** [comment]
#1282 adds the option for embedding an additional login widget as an iframe. This can be used together with the `:extra-static-resources` config option to deploy EDS. See CSCfi/rems-deploy#55 for an example of that.

**Comment by foxlynx** [comment]
Does not work with iFrame, so we used link instead. There is an issue on EDS for this: https://issues.shibboleth.net/jira/browse/EDS-29

**Comment by foxlynx** [comment]
Martin's feedback:

> Please change the title: "IDP select test bed" does not sound too ensuring 
> Could you add clarin.eu and eduuni (as configured in production)

Moving the issue back to backlog.
