### ISSUE TITLE
LBR: ID not used in Email

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#1266]
Email still uses year/running number instead of ID.
The mail does not say what resource(s) were applied for (unlike present REMS):

Dear matthies@csc.fi,
User matthies@csc.fi has submitted a new application 2019/82.
View the application: https://rems-lbr03.csc.fi/#/application/910
Please do not reply to this automatically generated message.

**Comment by opqdonut** [comment]
does present REMS use the catalogue item title or the resource id in the emails?

**Comment by mmatthiesencsc** [comment]
Yes, e.g.:
Hyvä Martin Matthiesen,

Jukka Vitanen on tehnyt huomiotanne vaativan hakemuksen 000 käyttää kielivaroja Finnish Text Collection.
Voitte hyväksyä tai hylätä hakemuksen: https://lbr.csc.fi/#/application/000

Älkää vastatko tähän automaattisesti luotuun viestiin.

**Comment by mmatthiesencsc** [comment]
We actually localized the email texts in the present production version.  They apparently are not added as part of the deployment?

**Comment by opqdonut** [comment]
Emails are currently sent using the configured default language.

**Comment by mmatthiesencsc** [comment]
The language is fine, I should have probably said customization, e.g. we call "resources" "kielivara" (which obviously makes only sense for the Language Bank). I have a feeling this customisation was added last year by creating a completely separate repository. How do we handle our own texts now?

**Comment by hukka** [comment]
I will make a separate issue about the translation customization. Currently it's a bit unclear how the operations of the LBR will be done, but we do have the capability to completely replace the translations for the email messages. It just adds to the op workload and the deploy scripts could go out of sync compared to what the REMS code expects.
