### ISSUE TITLE
how can I the demo data in REMS?

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#1273]
Dear REMS team,

`lein run test-data` add test data to REMS and I would like to edit this files so I can create my own users.

How can I do that?

thank you

**Comment by opqdonut** [comment]
You can create users by:
- the `/api/users/create` API
- inserting lines manually into the `users` table in the db
- or if you really want to edit the code, it's in `src/clj/rems/db/test_data.clj` . The relevant function is `create-users-and-roles!`.

**Comment by Masber** [comment]
where can I see an example of using /api/users/create endpoint? curl would be enough.

thank you

**Comment by opqdonut** [comment]
The user roles? To make the user a handler, just name them when creating a workflow. Commenters and deciders don't need roles, the handler can invite anybody he wants to comment/decide.

The owner (admin) and reporter (can see all applications) roles need to be set in the `roles` table in the db. There's no API for that yet.
