### ISSUE TITLE
Editing form_template.fields value does not reflect on application

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#1280]
Dear REMS team,

We have a large form and would like to change them on the fly. We tried editing the jsonb value in form_template.fields database field.

We expected this change to be able to reproduce on following catalog items created based on that new form template (form preview shows the changes). However applicants can't see the modifications.

Is there an easy way to change a form programatically?

thank you very much

**Comment by opqdonut** [comment]
There are a couple of things here.

a) There is some caching of application state. Restart REMS (or tomcat if running under tomcat) and you should see the changes.

b) Currently you also need to also edit the `application_form_item` and `application_form_item_localizations` tables (and perhaps `application_form_item_map` if you add/remove/reorder fields or `application_form_item_options` if you change options). We're in the process of migrating to using only `form_template`, but it's not done yet (see #913)

c) form editing API and UI will be implemented soon, see #865
