### ISSUE TITLE
Add link to Github hash/version for easier referencing.

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#1297]
I suggest that you add a reference to the Github version somewhere not too obvious for easier bug reporting. RCs had a link in the footer, that would be too much in production, but maybe a version string could be put into the admin page? Or the "Powered by CSC" could open a little "About" box when clicked.

**Comment by Macroz** [comment]
In the latest production versions this is shown in the browser console like so:
```
Version:  v2.25-0-gd55724d57
https://github.com/CSCfi/rems/commits/d55724d57ac262014b9a1be8643bd6357176029f
```

I guess this satisfies the requirement?

**Comment by jaakkocsc** [comment]
This seems to be there now, so closing the issue.
