### ISSUE TITLE
multiple sources of truth for authentication

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#1302]
Dear REMS team,

Would it be possible to have REMS to authenticate users against shiboleth and ldap? for instance in case the user does not belongs to the federated network then REMS would check ladap.

Is this possible?

thank you very much

**Comment by hukka** [comment]
It isn't possible at this moment, but wouldn't be very hard to do implement. Unfortunately it isn't prioritized right now. Is sending a pull request for this feature possible to you, if this is a blocker for you?

**Comment by mmatthiesencsc** [comment]
As a side comment: It is actually relatively easy to put a Shibboleth IDP in front of an LDAP server. I don't see the need for LDAP support in REMS.
