### ISSUE TITLE
Remove PDF button

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1314]
"muistaakseni olisi hyvä että aukeisi suoraan PDF eikä tarttis käyttää print to PDF toimintoja arkistointiin mutta siinä tapauksessa olisi parasta tehdä tulostus bäkkärissä niin että siellä renderöidään selaimella PDF-tiedosto joka siirretään käyttäjän selaimeen, näin ei tartte pitää yllä kahta eri näkymää hakemuksen tiedoista eikä myöskään stailata niitä"

**Comment by opqdonut** [comment]
So does this mean pdfs should be generated by simulating "print to pdf" on the server?

**Comment by opqdonut** [comment]
Use case is printing applications one-by-one.

Let's remove the PDF button and direct users to use "print to pdf". If bulk pdf export is needed later, let's create another ticket.
