### ISSUE TITLE
Implement ELIXIR Permissions API

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1319]
Implement the common permissions endpoint of the ELIXIR Permissions API.

It should be a new API endpoint, `/api/permissions`, which has
- [x] a GET method similar to existing entitlements endpoint outputting GA4GH Visas
- [x] a POST method for pushing new entitlements as GA4GH Visas to a configurable receiver

GA4GH Passport specification defines the [format of Visas](https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/ga4gh_passport_v1.md#passport-visa). In the context of the [specification overview](https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/ga4gh_passport_v1.md#overview), REMS is considered to combine functionalities of Passport Visa Assertion Repository and Passport Visa Issuer.

**Comment by hukka** [comment]
https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/RI_Claims_V1.md is a bit different from the swagger; authoriser is not used, and there's a possibility to list accepted licences.

This would need some discussion with a domain expert. I suppose that the source could be https://grid.ac/institutes/grid.20709.3c for LBR (that's CSC's grid URL) and https://grid.ac/institutes/grid.14758.3f for THL. by would be "dac", I suppose. Biggest hurdles are:
- linking users with the Elixir ID — I suppose we need #1234 for that
- figuring out URLs for resources, as currently we have just resIds
- deciding what we will use as expiry dates, as now we only use them when revoking entitlements
- do we need to list conditions that bind the access not just to the user's ID, but their status in their organization (e.g. if they stop being faculty, they won't have access)

**Comment by jaakkocsc** [comment]
Any differences from the RI spec in the swagger is an add-on feature requested by European Genome-Phenome Archive, and should be ignored — such as authoriser field. REMS should only implement specification for maximum compatibility.

**Comment by opqdonut** [comment]
see also #794

**Comment by opqdonut** [comment]
Waiting for the spec to stabilize. DL for new spec was 2019-08-20.

**Comment by jaakkocsc** [comment]
Current:
`
curl -X GET http://rems/api/entitlements -H "x-rems-api-key: demo" -H "x-rems-user-id: 08ea84fde95aca412f572d7b84823391beed05e8@elixir-europe.org"
[
{
"resource": "urn:hg:example-controlled",
"application-id": 11,
"start": "2019-09-17T05:48:51.457Z",
"end": null,
"mail": "teemu.kataja@csc.fi"
}
]
`

What is should be like:
`curl -X GET https://rems/api/permissions/08ea84fde95aca412f572d7b84823391beed05e8@elixir-europe.org -H "Permissions-Api-Key: demo"
{
"ga4gh_passport_v1": [
"eyJqa3UiOiJodHRwczovL2p3dC1lbGl4aXItcmVtcy1wcm94eS5yYWh0aWFwcC5maS9qd2tzLmpzb24iLCJraWQiOiJiMzQ5MmZkNiIsImFsZyI6IlJTMjU2IiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL2p3dC1lbGl4aXItcmVtcy1wcm94eS5yYWh0aWFwcC5maS8iLCJzdWIiOiIwOGVhODRmZGU5NWFjYTQxMmY1NzJkN2I4NDgyMzM5MWJlZWQwNWU4QGVsaXhpci1ldXJvcGUub3JnIiwiZ2E0Z2hfdmlzYV92MSI6eyJ0eXBlIjoiQ29udHJvbGxlZEFjY2Vzc0dyYW50cyIsInZhbHVlIjoiaHR0cHM6Ly93d3cuZWJpLmFjLnVrL2VnYS91cm46aGc6ZXhhbXBsZS1jb250cm9sbGVkIiwic291cmNlIjoiaHR0cHM6Ly9nYTRnaC5vcmcvZHVyaS9ub19vcmciLCJieSI6ImRhYyIsImFzc2VydGVkIjoxNTY4Njk5MzMxfSwiaWF0IjoxNTc2MjQyNzc1LCJleHAiOjE1NzYyNDYzNzUsImp0aSI6Ijg3NDIxZWM3LWFiNmYtNDhlOS04MjU1LTJjNDAzMGVjMzgxYSJ9.srs9uh7a8bUHVOgmiuiyaIOkG_bnJETaZ-Cna6cURNdR3nKM44eBXQo1e3jsEpiZCaTpc2oO_oxp6gd0j24ONAX5CeViRF3z2K1GFmQJxAcyHRxiGz8G7d4RjcTPIuOeb3z_qFg1pR5aPw_NZM9rJ6LM5L50LHoLqgHuax2ocgrop7CpmWc9NPUoG0errwpZgGnXfO0rGGAhGTp-vFBZDKCtJzH_EJ6KP4qL0CCiBTrS-ruDKNBESxDOX2NXzYlFC06fv5vfq4ZMrVBL5ewqECQA0SiRiZmhqfUHSrgbtU_8Tc8SGxkztlIN6FFQ88tvhHpJ2OEO8JeKWd87MHDXWA"
]
}
`
Decode using, e.g. https://jwt.io/

**Comment by jaakkocsc** [comment]
Here's the formal spec: https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/ga4gh_passport_v1.md#ga4gh-passport

REMS needs to implement Visas from the spec. AAI provider's OAuth2 AS will wrap visas in passport and passess that to the consumer.

**Comment by foxlynx** [comment]
REMS needs to push entitlements to a mediator component that then converts them to ga4gh_visa format.

**Comment by opqdonut** [comment]
related: #2344
