### ISSUE TITLE
Swagger-UI-given API calls with multiline content don't work

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1327]
e.g., creating a new user with example content value gives the following curl call:

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/octet-stream' -d '{ \ 
   "eppn": "string", \ 
   "mail": "string", \ 
   "commonName": "string" \ 
 }' 'https://remsdev.kaj.pouta.csc.fi/api/users/create'
```

but the receiving end doesn't parse the "\" signs correctly and gives an error. Without "\" signs the call works.

**Comment by opqdonut** [comment]
Ah right you mean the `\` (backslash) characters. They should be at the end of the line but for some reason they are followed by whitespaces. This might be fixed in swagger ui 3.
