### ISSUE TITLE
Unify the displaying of localized fields on admin pages

### ISSUE THREAD

**Issue by luontola** [CSCfi/rems#1334]
Currently there are three different styles in use for inputting localized texts on the admin pages. Some unification might make it prettier.

![three variants](https://user-images.githubusercontent.com/42678/59348195-3093b580-8d1f-11e9-8fe8-18ae0c054a16.png)

See #2113

- [x] figure out which style we want to stick with
- [x] change one page to use this style
- [x] develop nice utilities for working with this style
- [x] convert the rest of the pages (a big task!)

**Comment by marharyta** [comment]
As I went through the backlog, I noticed this one and thought that this is something that should have been prevented by using the ```/guide``` that we have. How much use/benefit we have for it in any case?
I am not implying anything, just want to get to the bottom of things here.

**Comment by Macroz** [comment]
The people who built the screens simply built them using separate components, varying approaches and at a different time, and without looking at the other pages / guide, so we ended up with a few different ways of showing similar things.

**Comment by jaakkocsc** [comment]
Should probably incorporate the feedback from stat also.

**Comment by aatkin** [comment]
gathered some screens that need unification, only create/edit views. three distinct styles

## 1. Title label, with fields with localization key under

![Screenshot 2022-07-20 at 14 25 29](https://user-images.githubusercontent.com/794087/179977503-9d32eaef-63de-4013-85fc-8cf2f8b66b20.png)

![Screenshot 2022-07-20 at 14 26 14](https://user-images.githubusercontent.com/794087/179977347-86591601-167f-402a-98eb-00ab58bc21c4.png)

![Screenshot 2022-07-20 at 15 10 10](https://user-images.githubusercontent.com/794087/179978491-7d5f0f56-591c-455e-b8a1-1ef09c7c7a58.png)

![Screenshot 2022-07-20 at 14 27 14](https://user-images.githubusercontent.com/794087/179977453-052691a1-86ae-4e29-acaf-fc5905a324b5.png)

![Screenshot 2022-07-20 at 15 11 59](https://user-images.githubusercontent.com/794087/179978816-9787d7d3-e473-4d1c-8ff5-2b2915bc57ca.png)

## 2. Field with title and localization key combined

![Screenshot 2022-07-20 at 14 24 42](https://user-images.githubusercontent.com/794087/179977617-b7b5169b-45b4-4315-8edf-238cf1fa0cd2.png)

![Screenshot 2022-07-20 at 15 12 57](https://user-images.githubusercontent.com/794087/179978978-af4e8ffd-b954-4c9d-a940-4e372c26ede9.png)

## 3. Localization key (in huge capitals), field with title under

![Screenshot 2022-07-20 at 14 26 52](https://user-images.githubusercontent.com/794087/179977788-73836da5-dee0-4b02-b403-3140bf67b8df.png)
