### ISSUE TITLE
Insert THL custom texts into welcome page

### ISSUE THREAD

**Issue by hukka** [CSCfi/rems#1345]
Update welcome text for THL

**Comment by jaakkocsc** [comment]
Here are the texts.
[Toivotut sisällöt REMS2-sähköpostiviesteihin_040719.pdf](https://github.com/CSCfi/rems/files/3577785/Toivotut.sisallot.REMS2-sahkopostiviesteihin_040719.pdf)

**Comment by Macroz** [comment]
Waiting for texts still

**Comment by opqdonut** [comment]
done in CSCfi/rems-deploy#146 CSCfi/rems-deploy#149
