### ISSUE TITLE
Application has "delete" button that does not actually delete the data

### ISSUE THREAD

**Issue by hukka** [CSCfi/rems#1357]
"Close" might be interpreted as closing the window, not losing access. Need a better name or a description that explains the function. The explanation also would function as a verification to avoid accidental deletions/closures

**Comment by okahilak** [comment]
How about doing the following changes:

![image](https://user-images.githubusercontent.com/49641103/61441348-1a949880-a94e-11e9-9d9c-50a2972c1c24.png)

Delete... -> Close application...

and

![image](https://user-images.githubusercontent.com/49641103/61441383-3009c280-a94e-11e9-9fa4-feeaef61d409.png)

Delete -> Close

![image](https://user-images.githubusercontent.com/49641103/61441416-3e57de80-a94e-11e9-9fbd-2d0ce31e068c.png)

Deleted -> Closed

It resolves the problems with the verb "delete" while still specifying that the user is about to close the application and not, e.g., the window.
