### ISSUE TITLE
Saving forms in editor should always show a succeeded/failed popup

### ISSUE THREAD

**Issue by hukka** [CSCfi/rems#1362]
The same status modalas application, to make sure that saving succeeded. Field specific failures can be hidden out of view with long forms.

**Comment by okahilak** [comment]
I think a more standard solution for this would be to scroll to the location of the first form field that is giving an error.

**Comment by hukka** [comment]
Sure, but we still should show a popup to match how the UI works elsewhere, so that it's clear when the button press has been processed and there just isn't some kind of delay or network problem.

**Comment by okahilak** [comment]
This issue seemed a bit complicated to me:

- In form creation, the form is validated in front-end, causing the errors to be more naturally shown next to the form fields, maybe with added scrolling to the location of the first error (which I think would be overall the most user-friendly way to show the errors).

- When filling out a form, the form is validated in back-end, causing the errors to be naturally shown in a pop-up.

I saw a recommendation somewhere that form validation would be better done completely in the front-end when possible, but I'm not sure how authoritative the source was.

Generally, I'd like to decrease the number of unnecessary pop-ups, as I think many web users are not accustomed to sites showing messages in pop-ups.

In any case, some kind of unifying would be nice, but I'm not sure which direction to take.

**Comment by luontola** [comment]
Popups are problematic from an accessibility point of view. Showing a message at the top of the page and focusing it automatically is much better. Form validation errors are shown as a list in the top of the page, with links to the fields in question, and the fields also have inline error messages.

**Comment by opqdonut** [comment]
Superseded by #1461 see also #1469
