### ISSUE TITLE
Specify browser support policy

### ISSUE THREAD

**Issue by hukka** [CSCfi/rems#1364]
IE is not currently supported, but different versions of Edge have very different capabilities.

The policy should not mention versions explicitly, but have built in deprecation (such as supporting latest 3 versions, or versions from last 3 years etc.).

**Comment by opqdonut** [comment]
- [ ] Find out browser stats / policies from users (THL and LBR)
- [ ] Write up a browser support policy in the repo

**Comment by opqdonut** [comment]
Discussion about current state:
- we test with fresh chrome and firefox
- we don't really test on mobile, we might test on desktop chrome in responsive mode

**Comment by opqdonut** [comment]
Lots of applicants use OS X. Consider adding Safari.
