### ISSUE TITLE
Collaborate on email wording/contents with THL, as with LBR

### ISSUE THREAD

**Issue by hukka** [CSCfi/rems#1366]

**Comment by jaakkocsc** [comment]
[Toivotut sisällöt REMS2-sähköpostiviesteihin_040719.pdf](https://github.com/CSCfi/rems/files/3577789/Toivotut.sisallot.REMS2-sahkopostiviesteihin_040719.pdf)

**Comment by opqdonut** [comment]
Everything done except the weekly reminders, which were split out to #1611

**Comment by opqdonut** [comment]
@jaakkocsc promised more polished wordings later

**Comment by jaakkocsc** [comment]
Product decision:
Wordings described in the attachment are considered REMS default. Customers may customise as they see fit, but these are the emails REMS sends out for each action. See also #1640 for adding signatures to these emails.
[Toivotut sisällöt REMS2-sähköpostiviesteihin_040719-HL.pdf](https://github.com/CSCfi/rems/files/3626289/Toivotut.sisallot.REMS2-sahkopostiviesteihin_040719-HL.pdf)

**Comment by opqdonut** [comment]
Due to consistency and ease of implementation, we'll use "[Application ID] [Application Title]" in all emails.

**Comment by opqdonut** [comment]
Further decisions / clarifications:
- use "resubmit" instead of "re-submit" due to dictionary
- use "review the application" when there is an action that can be taken, "view the application" if there is not
- send emails to (non-applicant) members for approve, reject and close, but not for return

**Comment by opqdonut** [comment]
I think the latest PR closes this issue. Further issues can be created for creating the customer-specific configurations.

**Comment by opqdonut** [comment]
Issues created, see above.
