### ISSUE TITLE
"More info" link to catalogue items

### ISSUE THREAD

**Issue by hukka** [CSCfi/rems#1369]
Similar to how LBR uses id links, but more general.

Could be edited in place.

**Comment by opqdonut** [comment]
Does this mean that catalogue items would get a new field that would get rendered as a "More info..." link? Would the field contain a URL or text?

**Comment by opqdonut** [comment]
hukka tells me it's supposed to be a URL

**Comment by foxlynx** [comment]
Specify the url to resource.

**Comment by opqdonut** [comment]
url should be localized
