### ISSUE TITLE
Auth0 support

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#1375]
Dear REMS team,

Does REMS supports SAML authentication instead of shiboleth?

thank you very much

**Comment by hukka** [comment]
Not right now, but most likely will be soon.

So far our customers have been using Shibboleth, but we are going to migrate to using a proxy for that. The proxy then would allow us to use either SAML2 or OpenID Connect. See #1234. This is pretty high on our backlog at https://github.com/CSCfi/rems/projects/1, currently just a few tasks above it.

Do you have any requirements regarding SAML2 or OpenID Connect, is only SAML available to you?

**Comment by Masber** [comment]
our intention is to use Auth0 as our identity provider so we are happy using SAML or any other protocol supported by Auth0 (the reason we asked about SAML is because it is similar to shibboleth which is already supported by REMS).

thank you

**Comment by hukka** [comment]
@Masber We are starting work on openid connect now. We are currently in the middle of the holiday season so rate of progress is a bit sporadic, but shouldn't be long!

**Comment by Masber** [comment]
thank you for letting me know @hukka

**Comment by Masber** [comment]
Hi,
just wondering whether there is any time frame for this feature?

thank you

**Comment by hukka** [comment]
@Masber Support should actually be in master already! We are just about ready to start switching our own instances over to OIDC, though we are not using Auth0 for that, but we did test the implementation locally using Auth0. If there are any problems, let us know.

**Comment by Macroz** [comment]
It's done and merged to master. Let us know if you have any questions. Closing this issue for now.

**Comment by Masber** [comment]
Hi,

is there any documentation in regards how to do the OpenID configuration?

thank you

**Comment by opqdonut** [comment]
the oidc config variables are listed in the config defaults: https://github.com/CSCfi/rems/blob/master/resources/config-defaults.edn

but we should add more documentation

**Comment by hukka** [comment]
Since you are aiming to use Auth0, it might be more instructive to look at https://github.com/CSCfi/rems/blob/master/dev-config.edn which is REMS' Auth0 config for development use.
