### ISSUE TITLE
Consider disabling "Change resources" feature for LBR

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1385]
They have said that they don't want the feature. Consider having the feature configurable and disabling it for LBR.

**Comment by mmatthiesencsc** [comment]
At a minimum the feature should work properly: At the moment changing the resource does not change the accompanying licences. So it is possible to accept licence A for resource A and then switch to resource B while still having only approved licence A. We then also need to make sure that the entitlements are handled properly. The easiest way forward is indeed to disable this feature for LBR.

**Comment by opqdonut** [comment]
License changing has been fixed, and entitlements should also work correctly. See #1377

**Comment by opqdonut** [comment]
Change resource works fine now. Won't implement hiding the button at this time.

**Comment by mmatthiesencsc** [comment]
Hi Joel, thanks fixing the issue was of course also an option :) Thanks!
