### ISSUE TITLE
Make resources editable

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#1390]
At the moment there is no way to edit a resource using the same ID. This is important to fix typos and similar issues.

Case in point:
https://lbr.csc.fi/#/administration/resources/50

The licence text is partly wrong (+LOC should not be there). I cannot fix this without creating a different resource under a different name. But his would break the whole logic behind the URN used, since the real resource has not changed.

Suggestion: Instead of making it impossible to edit resources, make them editable and track the changes.

**Comment by okahilak** [comment]
This is actually a part of an existing issue that is on backlog and was discussed in today's meeting: 

https://github.com/CSCfi/rems/issues/867

Therefore, I'm closing this issue and copied Martin's description from above to that issue.
