### ISSUE TITLE
"View workflow" still shows a list of licenses

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1458]
Even though workflows do not contain license information anymore. See screenshot below:

![image](https://user-images.githubusercontent.com/49641103/62528885-436dc680-b846-11e9-85f7-db1aa897fafb.png)

**Comment by luontola** [comment]
They still have license in the database, though there is no UI for adding them.

https://github.com/CSCfi/rems/blob/master/src/clj/rems/db/workflow.clj#L13-L18

**Comment by okahilak** [comment]
Ok, thanks, closing this issue.
