### ISSUE TITLE
Buttons are not aligned in tables, e.g., on "Create catalogue item" page

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1460]
See screenshot below:

![image](https://user-images.githubusercontent.com/49641103/62530879-fe4b9380-b849-11e9-956d-9187a6a9c575.png)

**Comment by okahilak** [comment]
Not sure how to do this properly. The "enable" button would need to know the size of "disable" button and vice versa. If min-width attribute of the buttons is set to wide enough so that the buttons are of the same size using Finnish translations, the buttons are way too wide when English translations are used:

![image](https://user-images.githubusercontent.com/49641103/62715821-e3278200-ba09-11e9-8451-750cb58a35e6.png)

**Comment by meericsc** [comment]
Fixed as part of https://github.com/CSCfi/rems/issues/501 since now the edit-button is a dropdown and the buttons are left-aligned
