### ISSUE TITLE
Make form creation validation more like form filling validation

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1461]
To ease up finding invalid fields, which are easily lost otherwise when the form is long.

**Comment by luontola** [comment]
A more usable solution is to show a summary of all fields with errors at the top of the page and there have links to each field. The same way as in the application.

**Comment by okahilak** [comment]
Hmm, I'm not sure offhand. Is that method used somewhere, where I could try it out?

An example case: Say that there are two fields that are missing. With the solution you proposed, I would press the link to the first field, fill it out, then scroll to the top of the page, press the link to the second field, fill it out, scroll to the bottom, submit the form.

If the submit button scrolls to the location of the first error, I would fill out the field, scroll to the bottom of the page (if the second invalid field is not easily visible), retry to submit, I would fill out the second field, scroll to the bottom, submit.

I don't see a large difference there, except that in the latter option, I don't have to keep track of the number of fields that I have already filled to be able to follow the correct link (which is easy in the case of two fields, but could be more cumbersome when there are more invalid fields).

For what it's worth, a large web store seems to show form validation errors as follows, without linking to the error location but with a large warning, showing some of the fields that failed validation, but not necessarily all at once (as in this case -- zip code is also missing, but it's not shown before full name and address are filled out):

![image](https://user-images.githubusercontent.com/49641103/62535484-33f57a00-b854-11e9-8abd-fb81ea0cdc0d.png)

**Comment by luontola** [comment]
Here is discussion about the options: https://webaim.org/techniques/formvalidation/

**Comment by opqdonut** [comment]
If the form is invalid:
- [ ] show failure popup with list of validation errors
- [ ] scroll to the top after popup closes
- [ ] show list of errors at the top of the page
- [ ] each error is a link that jumps to the field in question
If the form is valid:
- [ ] show a success popup
