### ISSUE TITLE
LBR: Change font spacing in headings

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1467]
LBR would prefer the UI to look like this (default spacing):

![image](https://user-images.githubusercontent.com/49641103/62691194-d9385b80-b9d6-11e9-8e0b-5b6d2e840f47.png)

instead of this (current):

![image](https://user-images.githubusercontent.com/49641103/62691224-ed7c5880-b9d6-11e9-8e11-623450a381bd.png)

**Comment by Macroz** [comment]
There is a way to add extra styles (and fonts) through this https://github.com/CSCfi/rems/issues/2586#issuecomment-900866366 but I created #2869 to track a more general solution.
