### ISSUE TITLE
Remove success pop-up windows

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1469]
LBR preferred success pop-up windows to not be shown to the user.

**Comment by opqdonut** [comment]
See also #1461 . Consider "flash" messages for success, perhaps accompanied with button animations.

**Comment by opqdonut** [comment]
Actually, this is superseded by #1461

**Comment by opqdonut** [comment]
(closed by accident)

**Comment by luontola** [comment]
Possibly related to #1501

**Comment by opqdonut** [comment]
Meeting on 2019-08-22: let's just do this.
