### ISSUE TITLE
Staging environment for LBR

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#1476]
- initialise a database from a dump of LBR data
- regularly (e.g. nightly) automatically run migrations from the latest master, and see if they pass
- environment can also be used for testing releases prior to pushing them to production
- no need to automatically get new dumps of production data, it can be updated manually

**Comment by foxlynx** [comment]
Blocked for the moment, branch: https://github.com/CSCfi/rems-deploy/tree/topic/lbr-staging
