### ISSUE TITLE
In Administration->Catalogue menu, the table has two "Resource" headings

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1484]
See screenshot:

![image](https://user-images.githubusercontent.com/49641103/62950253-59ecc280-bdf0-11e9-815b-2e50f2480f0e.png)

**Comment by Macroz** [comment]
Most of the UI uses "Resource" in place of "Catalogue item", but here we could use it, or something shorter like "Name" or even better use "Title" like it's called in the View/Edit.

**Comment by aatkin** [comment]
this was likely fixed in https://github.com/CSCfi/rems/pull/2898 but was forgotten to link & update
