### ISSUE TITLE
Implement auto-approve for an application

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1509]
Requirement: an application submitted by an authenticated user should be approved automatically. The approved application should have a named approver for back-tracking purposes.

This could be done so that, when creating a resource, an "auto-approve" checkbox is available and when checked, a named approver is asked as a required field. Furthermore, in global REMS configuration, there must a parameter enabling this auto-approve function, which by default is disabled.

This is for discussion only issue at this moment. Any ideas for implementation should be posted here as comments and then we pick up the most viable one.

**Comment by opqdonut** [comment]
This sounds like autoapprove could be a separate workflow since it applies to all applications for a resource.

Which handler actions should autoapproved applications support? Close probably. Return to applicant? Remark? Does there need to be a way to (re)process an autoapproved application via the normal dynamic workflow?

**Comment by jaakkocsc** [comment]
Auto-approve could be a separate workflow, but we've just managed to implement a dynamic workflow which should be able to handle all workflows. Would it be better to incorporate auto-approve into it, too?

Handler actions for auto-approved applications could be the same as for normal applications. But since the application is automatically approved immediately 'close' is the only action really possible for the handler.

**Comment by opqdonut** [comment]
Waiting for written specification from user.

**Comment by opqdonut** [comment]
Will implement as #1660
