### ISSUE TITLE
Remove success pop-ups when accepting terms of use and inviting a user

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1516]
As discussed in the meeting on Aug 16.

After the recent change of the page scrolling to the top when the pop-up is closed, the usability of these two actions suffer from the pop-up.

The page also indicates that the action was successful by changing the content of the page close to the action buttons. Thus, at least these two pop-ups can be removed.

**Comment by opqdonut** [comment]
I tried removing the popup from "add member" also, but the user list can grow so long that you won't see the added user.

**Comment by opqdonut** [comment]
Was able to remove some additional popups
