### ISSUE TITLE
Active flash message is not updated when language is changed

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1570]
If there is an active flash message shown on the page and the language is changed, the other parts of the page are updated with the new language but the old text in the flash message remains. See screenshot below:

![image](https://user-images.githubusercontent.com/49641103/64099954-3bd10d00-cd73-11e9-914e-c695f359a166.png)

**Comment by luontola** [comment]
A simple solution would be to just clear the flash message when the language is changed.
