### ISSUE TITLE
Submitting an application for disabled catalogue item gives the wrong error

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1571]
The error message shown to the user is "Submission failed. Check the following fields." without any further clarification. See screenshot below:

![image](https://user-images.githubusercontent.com/49641103/64111132-988cf180-cd8c-11e9-8958-239b5fbb8e4e.png)

Steps to reproduce:

1. Log in as Alice, create a new application for "Performance test resource 1", save the draft.
2. Log in as owner, disable the catalogue item "Performance test resource 1".
3. Log in as Alice, continue the application. Accept terms of use, fill in the form, try to submit.

**Comment by okahilak** [comment]
I looked into this a bit, but it seemed that it's not quite as straightforward as I thought.

When there is a disabled catalogue item, the error map returned by the API call is:

`{:success false, :errors [{:type :disabled-catalogue-item, :catalogue-item-id 6}]}`

whereas when there is a validation error, the API call returns, e.g.:

`{:success false, :errors [{:field-id 2, :type :t.form.validation/required}]}`

Both cases would need to be handled properly by the front-end, but currently it assumes that all errors that the API returns are of the latter kind.

**Comment by Macroz** [comment]
Noticed plenty of problems related to disabled items and change resources that have cropped up recently.

**Comment by Macroz** [comment]
Waiting for #1537 to be merged first.

**Comment by Macroz** [comment]
![Screenshot_2019-09-05_09-09-36](https://user-images.githubusercontent.com/823661/64316293-0fa8cc80-cfbd-11e9-9558-3becb947ea3d.png)

I changed the warning color back to danger and the message to refer to errors. I think this solves the immediate problems.
