### ISSUE TITLE
misc. flash message improvements

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#1580]
- don't use popup for failures. check at least:
  - [x] invite-member validation failure
  - [x] rems.actions.change-resources
  - [x] rems.actions.accept-licenses
  - [x] rems.administration.catalogue-items
  - [x] rems.administration.resources
- [ ] ~~fading / disappearing for flash message~~
- [x] mechanism for having multiple named locations for flash-messages on page. e.g. `:top`, `:application-members`, `[:attachment 13]`

**Comment by opqdonut** [comment]
See also #1578

**Comment by luontola** [comment]
A fading flash message may conflict with https://www.w3.org/WAI/WCAG21/Understanding/enough-time
