### ISSUE TITLE
Accessing attachments is broken, at least when session has timed out

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#1590]
For example: when accessing /api/licenses/attachments/123 without a session, we reply with code 401, which Chrome renders as "This site can't be reached."

- [x] check that accessing all attachments (licenses, application) works
- [ ] ~consider checking that the session is active in attachment link onClick callback~
- [ ] ~consider returning a nicer error page or another error code~
- [x] consider implementing a non-api endpoint for attachments that serves a redirect to the login page instead of 401

**Comment by luontola** [comment]
The "This site can't be reached" problem has already been fixed (it was due to unspecified content-type). Now the response shows just an "unauthorized" text.
