### ISSUE TITLE
Parts of action bar do not always fit in the window

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1614]
- [x] when submitting an invalid (non-complete) application, if the list of validation errors is long enough, the action bar scrolls out of the window (try THL form for example)

- [ ] when the handler adds terms of use, requests review, or requests decision, the dropdown menu, used for selecting the terms of use or the users to send the request to, is so low on the screen that the option list barely fits in the window with a full-sized browser window (with 1920x1080 resolution), most likely with a smaller resolution it does not fit properly.

**Comment by luontola** [comment]
The validation errors can be moved out of the actions panel after #1580 is done.
