### ISSUE TITLE
No error message if loading the application fails

### ISSUE THREAD

**Issue by luontola** [CSCfi/rems#1637]
For example visiting http://localhost:3000/#/application/999999 just shows an indefinitely spinning spinner.

**Comment by luontola** [comment]
Loading the catalogue has a similar issue. Looking into that as well.

**Comment by opqdonut** [comment]
- [ ] nicer 404 handler
- [ ] for a 500 or other error, the red failed box is ok, but text could be nicer than ": Failed"
