### ISSUE TITLE
Support for external register numbers

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1772]
When user submits an application, a register number should be issued for the application. The number is only issued at submission, not for drafts — i.e. when status changes to "Applied". Register number is generated by an external service. After register number has been generated only that register number should be presented for users/handlers/etc. instead of REMS internal id.

- ~support for attaching external-id to an application later (via a new event?)~ (in #1858)
- ~show internal id for applications that don't yet have an external id~ (in #1858)
- [x] @jaakkocsc to find out specification for the external service (in rems-deploy repository, doc folder)
- [x] make external service configurable

Using Tweb service, acknowledge vireilletulo for the application.

**Comment by jaakkocsc** [comment]
External service's (Tweb) specification is in the private repo.

**Comment by opqdonut** [comment]
Let's do #1858 first

**Comment by opqdonut** [comment]
Let's do something like this:
- [ ] implement a middleman that REMS pings with new applications
- [ ] the middleman fetches a new register number from the external service
- [ ] ... and issues a "assing external id" (#1858) command to REMS

**Comment by opqdonut** [comment]
see also cscfi/rems-deploy#129

**Comment by jaakkocsc** [comment]
Demoed with rhp in testing environment.
