### ISSUE TITLE
Throughput tracking for applications

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1793]
Assuming handlers have dozens of applications in processing and a fixed deadline for them, it would make life easier if UI would somehow show a "processing time left" counter, which could then be used to sort applications. Maybe even colour coding more urgent ones.

Tweb service needs to register when Findata handler has first opened an application.

**Comment by luontola** [comment]
If all applications have the same time limit since submission, isn't this need already filled by sorting by the "Sent" column?
