### ISSUE TITLE
Decision document

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1794]
After an application has been accepted/rejected, a formal decision document should be generated with signatures of the handler and the decision maker.

**Comment by opqdonut** [comment]
do #1829 first

**Comment by opqdonut** [comment]
#1829 was probably the wrong thing to do. The decision document will have a specific format (details to be delivered). We can't reuse the application page, instead we'll probably need to do something like generate a static html document and then convert it to pdf.

**Comment by opqdonut** [comment]
Let's make a separate piece of software that uses the REMS api and produces documents. Open questions:
- produce final document or a draft that will get finished manually?
- which format? (html? pdf? word?)
- how to listen for REMS events?
- how to deliver document? first guess: email to handler

**Comment by opqdonut** [comment]
see also cscfi/rems-deploy#129

**Comment by opqdonut** [comment]
Will apparently be implemented as an external service.
