### ISSUE TITLE
Ability to specify field ids in the form editor

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1804]
Field codes could be generated automatically, but could still be changeable by the user creating/editing the form.

**Comment by Macroz** [comment]
I'm assigning this to myself now because there is a dependency to #730 in the form of selectable values.

**Comment by opqdonut** [comment]
added Findata label because this might be useful in Findata's various integrations

**Comment by opqdonut** [comment]
Field ids should be stable when editing/copying a form.
