### ISSUE TITLE
Possibility to hide "Close" and "Approve" buttons from handler

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1806]
In governmental office, a handler (esittelijä) is not allowed to approve/reject applications but requests decision from an officer (päätöksen tekijä) after the application has been checked and is ready for a decision.

Also, after an application has been submitted it can't be closed but requires always a decision, even if the applicant withdraws it.

**Comment by opqdonut** [comment]
Ways to implement this:
- Implement a new "delegate decision" action, that gives a new `decision-maker` role to the given user, and he can approve/reject the application
  - Configure whether to show "delegate decision" or "request decision" action per organization
  - Possibly change the name of the old "request decision" action
- A new approver bot, that reacts to decision events by approving or rejecting the workflow
  - Would need to hide the approve button from "normal" approvers
- A new workflow (that reuses most actions from the dynamic workflow)

**Comment by opqdonut** [comment]
do #1830 first

**Comment by opqdonut** [comment]
will be done in #1830
