### ISSUE TITLE
When sorting table by column, the arrowhead showing the direction is missing

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1832]
That is, when a column is clicked on in the UI, the table is sorted by that particular column. There used to be an arrowhead showing if the table is sorted in the ascending or descending order, but in the current master (as of 2011-11-27), that arrowhead has gone missing.

**Comment by opqdonut** [comment]
not working in latest master (e723fdc77d4716202d22bcc5c7ea9a1debd7c98a)
