### ISSUE TITLE
Support pushing dataset permissions to external repository

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/rems#1847]

**Comment by opqdonut** [comment]
REMS supports pushing entitlements (permissions) over HTTP, see section *Entitlements* on https://github.com/CSCfi/rems/blob/master/docs/configuration.md . Would this be sufficient?

**Comment by jaakkocsc** [comment]
This is implemented by combining the functionality of two other tickets:
* https://github.com/CSCfi/rems/issues/2095
* https://github.com/CSCfi/rems/issues/1319
Both of these have been done, so this ticker will be closed.
