### ISSUE TITLE
Possibility to add an info button ⓘ after a field title

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1863]
Form field of type textbox may contain additional info text as placeholder. Other field types do not have this option, hence a small info button after the field title should be added providing either a hover style or a small popup info text.

**Comment by Macroz** [comment]
Could have some structure in the basic field for these:

**FIELD NAME** :information_source: 
Desciption
Help text
ACTUAL INPUT
*error if any*

**Comment by marharyta** [comment]
Planning to use this one: 
https://getbootstrap.com/docs/4.0/components/tooltips/

**Comment by opqdonut** [comment]
I've heard tooltips aren't accessible. We've used collapses for similar features previously, see for example the (?) button next to search fields.
