### ISSUE TITLE
Lock for search index is sometimes left on, causing search to not work

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1890]
It has happened twice now, first at vm1446.kaj.pouta.csc.fi on Dec 18, and the second time at LBR on Jan 08.

The problem manifests itself by giving 500 error when searching, e.g., on actions page, as well as the following message in REMS log (e.g., catalina.out):

```
tore.NativeFSLockFactory@27162e7f): files: [write.lock]
org.apache.lucene.index.IndexNotFoundException: no segments* file found in LockValidatingDirectoryWrapper(NIOFSDirectory@/tmp/rems-search-index lockFactory=org.apache.lucene.store.NativeFSLockFactory@27162e7f): files: [write.lock]
```

When it happens, the directory `/tmp/rems-search-index` contains only the lock file (`write.lock`) but no actual index files (`segment*`).

It can be fixed momentarily by deleting the lock (`/tmp/rems-search-index/write.lock`), after which the search index is re-generated.

**Comment by okahilak** [comment]
It happened again at Fairdata, noticed on Jan 15.

**Comment by foxlynx** [comment]
Again at Fairdata, noticed on 17th of February, restarted 25th of February.

**Comment by jaakkocsc** [comment]
Haven't seen this happening in a while. Reopen, if re-appears.

**Comment by Macroz** [comment]
Happened again with `nkr-rems-test`

**Comment by Macroz** [comment]
No news, is good news?
