### ISSUE TITLE
Custom API key roles for NKR

### ISSUE THREAD

**Issue by okahilak** [CSCfi/rems#1910]
NKR would want to have three different API keys for different components of the system: Finna and security proxy. Finna should not be able to perform tasks that security proxy does and vice versa.

Finna requests to REMS:

creates an applicant who can change their own information
applicant asks permission for a catalogue item
=> api-keys for roles user-owner and applicant

Security proxy requests related to applicants to REMS api:

get entitlements for an applicant
get applications for an applicant
Security proxy session closer requests to REMS api:

get valid entitlements for all applicants
close entitlements whose due date is past (security proxy defines the due date) = close the application
=> api-keys for roles reporter
new role application-closer: only allowed to close applications

**Comment by foxlynx** [comment]
Two components in the beginning: Finna and security proxy. Finna should not be able to perform tasks that security proxy does and vice versa.

Finna requests to REMS:
- creates an applicant who can change their own information
- applicant asks permission for a catalogue item

Security proxy requests related to applicants to REMS api:
- get entitlements for an applicant
- get applications for an applicant
Security proxy session closer requests to REMS api:
- get valid entitlements for all applicants
- close entitlements whose due date is past (security proxy defines the due date)

**Comment by opqdonut** [comment]
possible new design in #2125

**Comment by jaakkocsc** [comment]
See ADR011, and above mentioned new tickets. This one will be closed.
