### ISSUE TITLE
how to setup https with a certificate in rems

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#1980]
Dear REMS team,

We would like to set up https on our REMS test environment.
This is especially useful when integrating with auth0 OpenID as we need to specify Allowed Callback URLs under https protocol
Is there a documentation around how to setup https/certificate on rems?

Thank you very much
Manuel

**Comment by opqdonut** [comment]
Currently REMS itself doesn't support HTTPS. You should use a reverse proxy (e.g. apache or nginx) to provide HTTPS support. Unfortunately, we have no docs for setting up a reverse proxy but there is material on the internet.
