### ISSUE TITLE
Multiple resources with different licenses in UI

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#1999]
As an owner, when I go to the create catalogue item page,

if same resource exists with different licenses the UI does not distinguish them, i.e. it's impossible to know which resource to select.

**Comment by marharyta** [comment]
Can you maybe give a screenshot @jaakkocsc ?

**Comment by Macroz** [comment]
It's the create catalogue item page resource dropdown that displays just the name of the item?

**Comment by marharyta** [comment]
<img width="369" alt="Screenshot 2021-02-03 at 10 35 09" src="https://user-images.githubusercontent.com/7344718/106721260-1a7deb80-660d-11eb-9d62-4fbf6380a30d.png">
It doesn't look like the type of licence is currently exposed in the re-frame db

**Comment by marharyta** [comment]
I think the easiest would be to get licence from the ```queries.sql``` the licence and expose it into the catalogue ```get-catalogue-items```, what do you think @Macroz @opqdonut

**Comment by Macroz** [comment]
> I think the easiest would be to get licence from the `queries.sql` the licence and expose it into the catalogue `get-catalogue-items`, what do you think @Macroz @opqdonut

I think the resources are fetched from the database and the licenses are joined to them in the service layer so they should be available already. You are looking at the wrong place (it's not the catalogue but the resources ...)

**Comment by opqdonut** [comment]
Perhaps this helps:
![create-catalogue-item](https://user-images.githubusercontent.com/207385/106745319-97b75980-6629-11eb-8fd7-740cc3746006.png)

**Comment by marharyta** [comment]
Hmm, do we have the data model definition anywhere in the docs?

**Comment by Macroz** [comment]
You can have a look at it in `re-frisk` like Joel showed or from the https://rems-dev.rahtiapp.fi/swagger-ui/index.html#/resources/get_api_resources too. The relevant code can also be seen elsewhere (the localized names of the licenses).

**Comment by marharyta** [comment]
Thanks a lot @Macroz

**Comment by marharyta** [comment]
I think my initial idea was pretty close, though. We do fetch catalogue items from resources and we do not expose licences in that call.

**Comment by Macroz** [comment]
I am confused at what you are saying, so are we talking about the same thing:
- create catalogue item admin page
- the select resource dropdown (these should show the license names)
- resources are fetched from /api/resources which joins the licenses to every resource and contains the localized name too

**Comment by opqdonut** [comment]
The confusion was cleared up on flowdock. I also updated the ticket description to be a bit clearer!
