### ISSUE TITLE
Bug: Option field value not visible in UI

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#2000]
In NKR environment selected option value is not shown in UI for one application. Deploy new version (not before 13.2.) and check that the problem does not appear anymore. Could not reproduce with new applications in either NKR environment or remsdev.

**Comment by foxlynx** [comment]
Option value was submitted somehow wrong to rems, should be option id. Fixed now in client end, but should rems throw an error or sth?

**Comment by Macroz** [comment]
Closing this. Missing feature is in #2117
