### ISSUE TITLE
dev_db.sh not starting postgres container

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#2005]
Hi,

I run ./dev_db.sh which fails and postgres:9.6 container is unable to start.

This is the error from the container:
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD for the superuser. Use
       "-e POSTGRES_PASSWORD=password" to set it in "docker run".
       You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
       without a password. This is *not* recommended. See PostgreSQL
       documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

Any thoughts?

**Comment by Masber** [comment]
A workaround is changing first line in dev_sb.sh file to the one below
`docker run --rm --name rems_test -p 5432:5432 -d -e POSTGRES_PASSWORD=password -e POSTGRES_HOST_AUTH_METHOD=trust postgres:9.6`

**Comment by Macroz** [comment]
Hi, seems like this behavior has changed in the later postgres 9.6 labeled images. When I remove my "old" postgres 9.6 image and download the latest I get the same problem. I will add this to our backlog.

**Comment by Macroz** [comment]
This looks like the culprit https://github.com/docker-library/postgres/pull/658
