### ISSUE TITLE
Support multiple organizations per user

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2035]
e.g. eDuuni sends multiple groups separated with `;`. Figure out what semantics multiple groups should have and support them.

- [ ] load user organizations from idp
- [ ] configurable separator
- [ ] user is given rights of all organizations

**Comment by opqdonut** [comment]
check what the actual use case is with NKR

**Comment by jaakkocsc** [comment]
Apparently, this ticket is irrelevant. Maybe a broke phone mishap.
