### ISSUE TITLE
Viewing an application should be logged as an event

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2057]
Currently, only actions are logged as events on an application. However, it would be necessary to log also who has opened the application just to view it (handlers, specifically) in order to maintain a good audit log.

**Comment by opqdonut** [comment]
- [ ] Use a new database table to log all API calls
- [ ] Logs available with reporter role
- [ ] API for reading logs

Future development:
- filtering/searching logs
- UI for logs
- export for logs

**Comment by jaakkocsc** [comment]
This might also solve https://github.com/CSCfi/rems/issues/2013 since system log does not need to contain user information anymore.
