### ISSUE TITLE
config-default.edn contains syntaxt error

### ISSUE THREAD

**Issue by sherzinger** [CSCfi/rems#2070]
Hi,

Instead of `file` it should be `filename` I believe. `file` results in application startup errors.
https://github.com/CSCfi/rems/blob/master/resources/config-defaults.edn#L82

I'd also recommend not using highly edn specific syntax in this example file (or document it better) as most admins will likely not know what `#_ ` stands for and are confused when the settings are not applied.

**Comment by opqdonut** [comment]
thanks, good catch!
