### ISSUE TITLE
support for entitlement end dates

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2123]
- [ ] configurable default length for entitlements
- form can have a field for proposed end date
- [ ] handler/decider can (optionally) select end date as part of approve action
  - [ ] the end date is set in entitlement immediately when it is created
  - [ ] event log should also show the end date: "Handler has approved the application. The entitlement ends 2021-03-04"
- no need for automation that closes the application: applications can stay in the approved state

**Comment by opqdonut** [comment]
doesn't need to be a bot, could also be part of the approve action
