### ISSUE TITLE
Multiple "only-if" visibility constraints

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2163]
It should be possible to add multiple `only-if` constraints in the sense that one OR the other answer makes the field visible. We can do this by having the user enter multiple values instead of just one.

- [ ] possibility to add multiple values considered with OR

**Comment by Macroz** [comment]
I think I tried to make it flexible but we didn't decide AND/OR at the time of the original implementation yet. Also the requirement / UI was then for only one.
