### ISSUE TITLE
OIDC logout should revoke session token at AAI

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/rems#2176]
### Description
Session token from OIDC authentication should be revoked/invalidated at AAI's side when logging out from a service.

### Issue
Currently when logging out from REMS with OIDC authentication, the session token at AAI's side is not revoked/invalidated, and as such, stays active/valid. A user can log back in to REMS without re-authentication (or other services using the same AAI), because the session token is still active. This token can be re-used in other services, and as such, is some kind of a security vulnerability.

### Expected Behaviour
The logout process should make a request to the AAI issuer to revoke/invalidate the session token, so that it may not be re-used for any other purpose.

### Example
Taking ELIXIR AAI as an example, for OIDC token revocation, the revocation endpoint can be found from the OIDC endpoint documentation at https://login.elixir-czech.org/oidc/.well-known/openid-configuration.

This listing displays the `revocation_endpoint` key, which has the value of `https://login.elixir-czech.org/oidc/revoke`. This endpoint can be requested with `HTTP BasicAuth` using `client id` and `client secret` for authentication, and sending the token in the `token` query string, e.g. `/oidc/revoke?token=xxx`.

**Comment by Macroz** [comment]
Some ideas to consider also:
- session refresh in the background
- session invalidation to cause revocation in the background
- synchronous revocation while clicking logout

**Comment by opqdonut** [comment]
We decided to start with doing a revoke on explicit logout (i.e. the user clicking the logout button). We'll tackle session timeouts later.

**Comment by opqdonut** [comment]
@teemukataja are you sure revoking the access token is enough to force the user to log in again? At least with the Auth0 server (which we use for development), a SSO cookie also needs to be cleared: https://auth0.com/docs/logout . Are there docs for AAI logout functionality?

**Comment by opqdonut** [comment]
Consider also adding support for `end_session_endpoint`
- https://openid.net/specs/openid-connect-session-1_0-17.html
- https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-logout-openid-connect

**Comment by opqdonut** [comment]
CSC AAI proxy doesn't support logout so let's just stick to supporting revoke for now.
