### ISSUE TITLE
Text input can be really slow

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2181]
E.g. when filling a long form.

This also makes us need slow input in browser tests.

The frontend is probably doing too much work per keypress.

**Comment by Macroz** [comment]
Administration editors (especially form editor) suffers from the too coarse re-frame subscription. Every field and its part depends on the whole form model so everything is updated on every keypress. We should use fine-grained subscriptions. A similar issue happens with a really long application.
