### ISSUE TITLE
Improve events view

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2202]
The events are shown grouped and sorted by time for each application. There are some improvements that can be made to e.g. clarify them.

- [ ] add a reasonable example of the complete events view component to the component guide. Now there is only examples of individual events.
- [ ] emphasize grouping of related events (review + comment). This could be by a border (e.g. dashed is in use in the admin side) or by a little bit more whitespace for `.event-group`
- [ ] extract the slightly complicated logic of `application-state` `event-groups` to a function
- [ ] add unit tests for the extracted function

**Comment by opqdonut** [comment]
ended up removing the grouping in #2251 so closing this
