### ISSUE TITLE
Configure Jetty to not reveal version information

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2216]
Our Jetty instance reveals its version number when you e.g. `curl -v https://rems-dev.rahtiapp.fi/`. This is best hidden.

- [x] hide Jetty version number i.e. `Server` response header
- [ ] bonus: hide other unnecessary headers
- [ ] bonus: check that headers are sensible

```
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 29 Sep 2020 05:53:39 GMT
< Content-Type: text/html;charset=utf-8
< Set-Cookie: ring-session=68c3ae46-84d0-4e20-9fd2-528da781486e;Path=/;HttpOnly;SameSite=Lax
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< Content-Length: 1850
< Server: Jetty(9.4.31.v20200723)
< Set-Cookie: 777388ba0ea525baeec811d03a1e5f88=79f4e1512640dbc72a83874ddd8eb11d; path=/; HttpOnly; Secure
< Cache-control: private
< 
...
```

**Comment by opqdonut** [comment]
The cache-control header was checked in #2484. The remaining extra headers are

```
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
```

- It looks like a `Content-Security-Policy` header could replace `X-XSS-Protection` and `X-Frame-Options` according to MDN [see here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection), [and here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)
- `X-Content-Type-Options` seems like it's still relevant according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)

**Comment by opqdonut** [comment]
some follow-up in #2536
