### ISSUE TITLE
More clear event list

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2233]
Customer explanation:
Events-listan tapahtumat kerääntyvät siihen nyt hieman hassusti, sillä uusin ei enää olekaan aina ylimpänä. Sen sijaan arviointipyyntöjen vastaukset tulevan itse pyynnön alle, mutta niin, että sitä ei visuaalisesti ole mitenkään helppo hahmottaa. Uusin toimenpide voi siis olla pitkällä alhaalla listassa, jos arviointipyyntöjä on lähetetty useille henkilöille ja sen jälkeen hakemus on vaikka käynyt täydennettävänä hakijalla. Ymmärrän kyllä ajatuksen tässä taustalla, mutta asia olisi huomattavasti helpompi hahmottaa jos nuo ”vastaukset” johonkin toiseen eventtiin olisivat esim. hieman sisennettyinä tai jotenkin muuten visuaalisesti hahmotettavissa, että mitkä tapahtumat kuuluvat mihinkin kokonaisuuteen.

**Comment by opqdonut** [comment]
Let's see what the customer says about the new design :)
