### ISSUE TITLE
Update customized emails to include the new email to applicant when submitting an application

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2256]
Check all the installations and update the customized emails to include the new emails that are sent to the applicant when applying.
- [x] THL
  - [x] Looks like THL extra-translations/en.edn contains the same texts as master. Clean THL translations up.
- [ ] Findata
- [ ] LBR

See #2234 #2254

**Comment by opqdonut** [comment]
We have tons of configuration to do for LBR anyway when it gets upgraded, we can handle that separately

**Comment by Macroz** [comment]
@jaakkocsc is this issue still valid? I.e., does someone need to update emails for Findata or can we just close this?
