### ISSUE TITLE
Automatic delete of drafts after x days

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2282]
- [ ] scheduled job that happens ~ once a day that will delete old drafts if expiration is defined
- [ ] configuration for defining how soon drafts expire
- [ ] UI note for catalogue/drafts and applications about expiration of drafts if configured
- use warning color for expiring drafts?

**Comment by opqdonut** [comment]
no need to do this: drafts aren't shown to anyone except the applicant any more (#2268), and the applicant can delete drafts (#2219)
