### ISSUE TITLE
DUO field type

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2314]
Implement a field type that lets the user pick from predefined DUO (Data Use Ontology) codes. There are a ton of these so some sort of search/completion if needed.

- [ ] store DUO codes in the database
  - [ ] machine readable id (`DUO:1234567`), "shorthand", english description (see https://github.com/EBISPOT/DUO/blob/master/duo.csv)
  - [ ] support for other localizations in the future?
  - [ ] populate some example codes in test-data
- [ ] api for fetching DUO codes
- [ ] new `duo` field type
  - [ ] in form editor
  - [ ] when filling in application, fetch DUO codes from API and offer a nice searchable list
  - [ ] user can pick multiple DUO codes

**Comment by opqdonut** [comment]
split out from #776

**Comment by jaakkocsc** [comment]
The latest released version of the DUO OWL files is always available at http://purl.obolibrary.org/obo/duo.owl and can be browsed at http://purl.obolibrary.org/obo/DUO_0000001. Documentation can be found online at https://github.com/EBISPOT/DUO.

**Comment by jaakkocsc** [comment]
A feature request here: https://docs.google.com/document/d/100RDtOI-Tp_pr2AYXUi-bZ_w4Lm61ol83_knC26jBWU/edit#heading=h.o5dw7mwgnxvg

**Comment by Macroz** [comment]
We have now implemented DUO as an experimental feature, a little bit different than in the task here (since we learned new things). Further tasks in #2763.
