### ISSUE TITLE
Unify (optional)

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2318]
Our translations have some unnecessary variation in the `(optional)` text, for example in Swedish:
- Fält beskrivning (valfritt)
- Max antal tecken (valfri begränsning)
- Exempel (frivilligt)

Let's go with `valinnainen` for Finnish ~ `optional` for English ~ `valfritt` for Swedish.

- [x] unify use of (optional) in the language texts
- [x] use valinnainen in `fi.edn`
- [x] use optional in `en.edn`
- [x] use valfritt in `sv.edn`

**Comment by Macroz** [comment]
Consider merging at least #2296 first.

**Comment by Macroz** [comment]
@MalinAhlberg, since you kindly fixed the Swedish translations, do you have an opinion on this task i.e. which option would make most sense for Swedish?

**Comment by MalinAhlberg** [comment]
All of them works, but I would vote for "valfritt".

**Comment by michellymenezes** [comment]
I just opened a quick PR which should fix this. Please provide any necessary feedback as my native language is Portuguese 😅

**Comment by Macroz** [comment]
Thank you for the contribution!
