### ISSUE TITLE
Key management for generated GA4GH Visas

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2352]
- [x] serve the public key that can be used to verify the JWS signature
- [x] set the `jku` header parameter
- [x] figure out how to configure keypairs (generate at startup? files pointed to by config? embedded in config?)
- [x] figure out how to deploy keys
  - [x] via ansible
  - [x] in docker images (e.g. rahti) 

Spec: https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/ga4gh_passport_v1.md#passport-claim-format

**Comment by jaakkocsc** [comment]
I'd add here specification for Embedded Token Issuer: https://github.com/ga4gh/data-security/blob/master/AAI/AAIConnectProfile.md#conformance-for-embedded-token-issuers
REMS should fulfil clause 1.ii, not 1.i which would be ELIXIR AAI service
