### ISSUE TITLE
Field description fixes

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2354]
- [x] saving a field without all localizations for the field description loses the texts. It should rather be a validation error.
- [x] remove support for field description for the label type
- [x] check that all other field types have a working field description

**Comment by Macroz** [comment]
@marharyta have you done the third bullet too? I mean did you (manually) check that each field type is sensible now and displays the field description correctly? Label obviously is done but I'm wondering if we have some type that doesn't work yet.

**Comment by marharyta** [comment]
@Macroz yes, I did check them manually
What do you suggest? Should we write more tests or?

**Comment by Macroz** [comment]
I was asking only to confirm that this task is completely done. It can be then checked and closed. I think we don't need tests for all of them, the importance is quite low.
