### ISSUE TITLE
API/Application call requires query to be written twice 

### ISSUE THREAD

**Issue by emiliaLipponen** [CSCfi/rems#2360]
Tämä on varmaan virhe; miksi api-kutsuun täytyy laittaa kahdesti query, jotta kutsu toimii? Esimerkki toimivasta pyynnöstä: 'https://%s/api/applications?query=query=state:%s' % (settings.REMS_HOST, application_state)

**Comment by opqdonut** [comment]
Weird, something like
```
curl -X GET "https://rems-dev.rahtiapp.fi/api/applications?query=state%3Aapproved" -H "x-rems-api-key: 42" -H "x-rems-user-id: handler"
```
works for me, but
```
curl -X GET "https://rems-dev.rahtiapp.fi/api/applications?query=query=state%3Aapproved" -H "x-rems-api-key: 42" -H "x-rems-user-id: handler"
```
doesn't (returns empty list).

**Comment by Macroz** [comment]
If this is still relevant, we can reopen, but let's close for now, because we were unable to reproduce.
