### ISSUE TITLE
Improve application UI and UX by placing logo in the upper left corner as it is a common prcatice

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2363]
Currently the logo is in the center.
The research suggests it is bad UX practice: [https://www.nngroup.com/articles/centered-logos/](https://www.nngroup.com/articles/centered-logos/)

I suggest to follow a better UX convention and place the REMS logo in the upper left corner of navigation header as a link to homepage. 

Should support hero image for some customers and left-upper logo for navigation otherwise

- check themes from deploy repo

**Comment by Macroz** [comment]
Have to remember that each instance of REMS has their own logo, colors etc. that may or may not work the same. This like other major (cosmetic) changes to the UI, should be tested against all the instances(themes, and provided that it changes a lot, approved by each of the instances.
