### ISSUE TITLE
Better default font support for Visually Impaired: https://www.luciole-vision.com/luciole-en.html

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2364]
Some customers use their custom fonts, but we should have a possibility to change into Luciole font for people whose browser settings are configured to visual impairments.

This could be the default font for the test env and fallback font for customers.

- [x] Request web font
- [x] Make sure they gave permission to use the font with out licence
- [ ] Integrate font into app 
- [ ] Fix Font Issue where the font is not properly vertically centered.

**Comment by Macroz** [comment]
End result was that the font didn't work for us and it couldn't get fixed.
