### ISSUE TITLE
Repeating fields/rows

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/rems#2404]
Feature request: Repeating fields/rows

A form field with a row containing multiple fields and a button to `add` or `remove` rows.

Purpose: For gathering a list of data, e.g.
| Name            | Email                  |
|-----------------|-----------------------|
| Alice            | alice@email.com |
| Bob             | bob@email.com  |

`Add Row` `Remove Row`

**Comment by Macroz** [comment]
Also consider types mobile phone and IP address for field types.

**Comment by opqdonut** [comment]
See also https://github.com/CSCfi/rems/blob/master/docs/architecture/009-review-and-form-model.md

**Comment by Macroz** [comment]
We decided to plan this ticket next and split the new types (phone, ip) as separate tasks.

**Comment by opqdonut** [comment]
Preliminary plan:
- [ ] implement "simple table" component
  - question: how to store the field ansers?
    - option 1: CSV as string
    - option 2: JSON string
    - option 3: allow JSON objects in `field/value`. Will require schema & backend refactors.
- [ ] while implementing simple table, keep in mind possibility of adding column types
- consider add column types (email, text) to simple table immediately, if it is easy to do so
- in the future, implement "ip address" and "phone number" field types
- in the future, add ip address and phone column types to simple table

**Comment by opqdonut** [comment]
split out two tickets, #2551 and #2552

**Comment by opqdonut** [comment]
#2551 simple table component implemented

**Comment by opqdonut** [comment]
closing this: the rest of the ticket is in #2590 and #2552
