### ISSUE TITLE
"Email (from identity provider)" misused in UI

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2434]
After inviting a member by email, their user-entered email address is labeled "email (from identity provider)".

- [x] check all the uses of `:t.applicant-info/email` and consider if `:t.actions.member-email` is a better translation key
- [x] consider refactoring translation keys, for example having a different key for "(from identity provider)", or renaming the current `:t.applicant-info/email` to `:t.applicant-info/idp-email`

Screenshot:
![wrong-email](https://user-images.githubusercontent.com/207385/98516921-d41b2980-2275-11eb-9961-009b061e4f3e.png)

**Comment by marharyta** [comment]
<img width="381" alt="Screenshot 2021-01-23 at 22 42 38" src="https://user-images.githubusercontent.com/7344718/105613634-65596100-5dcc-11eb-8ac1-9ee671e97c74.png">

**Comment by marharyta** [comment]
<img width="1414" alt="Screenshot 2021-01-23 at 22 53 58" src="https://user-images.githubusercontent.com/7344718/105613863-e36a3780-5dcd-11eb-8fb4-0f12172e849d.png">
It is apparently possible to get to the profile page without logging in

**Comment by marharyta** [comment]
<img width="1348" alt="Screenshot 2021-01-23 at 22 55 22" src="https://user-images.githubusercontent.com/7344718/105613885-157b9980-5dce-11eb-945e-4369335f5435.png">
from https://rems-findata-demo.rahtiapp.fi/profile

**Comment by marharyta** [comment]
<img width="227" alt="Screenshot 2021-01-23 at 23 07 40" src="https://user-images.githubusercontent.com/7344718/105614107-ccc4e000-5dcf-11eb-96e3-2c422039101f.png">
this one is actually something I have been wondering about for some time, the indicator of the icon here is "settings" but the link and text lead to profile. The "human" icon is usually the profile ones.

**Comment by marharyta** [comment]
I would say That maybe we can just say "email" for the email input and have the info box that specifies the type of the email? Like, I would say a microcopy such as "Email" and info box: "from YOUR login identity provider"?

**Comment by marharyta** [comment]
<img width="876" alt="Screenshot 2021-01-24 at 0 36 49" src="https://user-images.githubusercontent.com/7344718/105615997-4236ad80-5ddc-11eb-9160-fd2937c4ae74.png">
I guess the invitation should not have it for sure?

**Comment by marharyta** [comment]
<img width="937" alt="Screenshot 2021-01-24 at 0 41 54" src="https://user-images.githubusercontent.com/7344718/105616101-fc2e1980-5ddc-11eb-8cd7-4c5749d07dd8.png">
The email is saved after the invitation is sent, is that expected behaviour?

**Comment by opqdonut** [comment]
> I would say That maybe we can just say "email" for the email input and have the info box that specifies the type of the email? Like, I would say a microcopy such as "Email" and info box: "from YOUR login identity provider"?

Yes, that sounds good, but we still need to make sure "from the identity provider" is shown only when it is true.

**Comment by marharyta** [comment]
So, I went through some ```http://localhost:3000/guide``` examples
If I remember correctly the Invited members cannot have the identity provider note?
<img width="898" alt="Screenshot 2021-01-27 at 18 31 48" src="https://user-images.githubusercontent.com/7344718/106021886-ee72df80-60cd-11eb-8511-3ee974fe0c5f.png">

**Comment by marharyta** [comment]
<img width="911" alt="Screenshot 2021-01-27 at 18 41 56" src="https://user-images.githubusercontent.com/7344718/106023298-583fb900-60cf-11eb-8a4b-bd37a3b83208.png">
I am also wondering weather this is more confusing or helpful to have two separate emails: one for notification another one for log in

**Comment by Macroz** [comment]
Member invite email is written by the user so it's not from the IdP.

The `:email` field is not for login, it's the one provided by the IdP attributes for contact info to the user. However the user can override it if they rather want to receive notifications elsewhere.

**Comment by marharyta** [comment]
<img width="1242" alt="Screenshot 2021-04-29 at 11 21 59" src="https://user-images.githubusercontent.com/7344718/116522029-5d362380-a8dd-11eb-9c5f-0e14ec65730c.png">
The way I understand, on the settings page, it is all good?

**Comment by opqdonut** [comment]
yep, seems to be

**Comment by marharyta** [comment]
<img width="930" alt="Screenshot 2021-04-29 at 12 00 50" src="https://user-images.githubusercontent.com/7344718/116526700-8d33f580-a8e2-11eb-882f-4d0a2f3eae59.png">

Ok, So I would remove the line from here, from the applicant, does that make sense?

**Comment by marharyta** [comment]
<img width="941" alt="Screenshot 2021-04-29 at 12 03 29" src="https://user-images.githubusercontent.com/7344718/116527049-ec920580-a8e2-11eb-9bef-7e8b16bc155d.png">
This one, maybe we can have it inside the applicant but not the invited member - the provider. tag that is

**Comment by opqdonut** [comment]
We should show it only when the email is guaranteed to be from the identity provider. For the invited member it should clearly be just "Email". For the Applicant, it probably needs to be just "Email", but you can check by adding a notification email notification@example.com for the owner and checking if that field shows notification@ or owner@example.com.

**Comment by marharyta** [comment]
ok!
So what info in the state would suggest the email of the applicant is from the provider? I am wondering whether the role would be enough
