### ISSUE TITLE
Only download current field attachments via "All attachments (zip)"

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2453]
- [ ] add a `?current-field-values-only` query parameter to the `/api/application/:id/attachments` endpoint
  - when this option is enabled, the produced zip should only contain the current values of attachment fields and not previous values, or comment attachments
- [ ] use this option in the UI zip button
- [ ] consider rewording the button

**Comment by opqdonut** [comment]
I had a quick look at the code and it looks like we copy the attachments one-by-one, and only copy the attachments used in field answers. So at least the code tries to do the right thing.

**Comment by opqdonut** [comment]
Original bug report from Findata

> Kun hakija on kopioi vanhan hakemuksen uudeksi hakemukseksi REMSissä, uudelle hakemuslomakkeelle siirtyvät ilmeisesti myös vanhan hakemuksen liitteet. Kollegani Hanna huomasi juuri, että vaikka hakija on tällaisessa tapauksessa poistanut edellisen hakemuksen liitteet ja korvannut ne uusilla (kyseisen hakemuksen omilla), edellisen hakemuksen liitteet ovat kuitenkin jääneet jotenkin hakemukseen mukaan, sillä kun hakemuksen käsittelijä ottaa kaikki hakemuksen liitteet zippinä ulos, mukana tulevat sekä uuden että vanhan hakemuksen liitteet.

**Comment by opqdonut** [comment]
Copying an application also copies the attachment, by design. However, after changing the attachment and submitting the application, the handler sees both attachments via the "show changes" feature. This is the real bug.

**Comment by opqdonut** [comment]
Oh ok, that's by design too. #832 specifies:

> handler can diff changes compared to the old application

**Comment by opqdonut** [comment]
There are some corner cases here that don't work quite right. For example:
- create new draft
- add attachment blue.png
- copy as new application
- change attachment in new application to red.png
- submit new application
- now handler sees blue & red.png

The line that seeds the diff for a copied application is https://github.com/CSCfi/rems/blob/de3fa7a8c63f61703c54b4ac6d647fe7ff8e5471/src/clj/rems/application/model.clj#L228

**Comment by opqdonut** [comment]
Let's find out what the user requirements are for the zip feature and remove unnecessary clutter from the zip. We can leave the current "full zip" functionality in the API for archiving use.

**Comment by opqdonut** [comment]
Rewrote ticket description

**Comment by opqdonut** [comment]
This will effectively need https://github.com/CSCfi/rems/issues/2571

**Comment by opqdonut** [comment]
It's been a bit unclear whether the users want the zip to contain only the (current versions of) application attachments, or perhaps also the event attachments.

Let's start by implementing just the application attachments.
