### ISSUE TITLE
Enable non-HTTPS OIDC connection to local IdP

### ISSUE THREAD

**Issue by katpavlova** [CSCfi/rems#2462]
As a developer seeking to connect REMS to a keycloak IdP for local development and testing, I would like to have REMS authenticate via OpenIDConnect with a local keycloak realm of my choosing.

Currently, the `:oidc-domain` parameter only supports connections over HTTPS. Attempting to connect to a local keycloak instance (ie: at `http://localhost:3000`) yields a `Connection Refused` when `docker-compose up` is run.

Please add a `:oidc-protocol` parameter to the config file, with the following values supported: `http`, `https`.
EDIT: Alternately, the solution suggested by @opqdonut below sounds even better.

**Comment by opqdonut** [comment]
Let's add support for specifying the full URL of the OIDC configuration. It'll be useful for all sorts of things like this.
