### ISSUE TITLE
Push permissions to EGA

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2466]
Plan
- [x] store handler api key in user secrets (new table)
- [x] show that a handler has an api key in the UI, on the profile page
  - don't send the actual api key to the frontend
  - [x] button for fetching a new api key
  - [x] button for deleting api key
- [x] when handler logs in, and there is no api key but EGA is enabled, show message
- [x] store handler of the entitlement into the entitlements table
- possibly store decider into the entitlements table?
- [x] use handler's api key to authenticate Visa push to EGA in the entitlement poller, also need to update/delete
- [x] approver bot support for entitlement push (configured through command-line)
- [x] configure test environment
- [x] More info support for "EGAD..." resources.
- [x] Handler must generate an API-Key from Profile page
- [x] Manual update for handlers
- [x] write ADR (check / link to ga4gh.md that has EGA info)

[Final specs](https://docs.google.com/document/d/1FTzUYAfV5d2a0zoDkbY9Iy_L5NbSAnHeWnmY2NIrY8M/edit)

[Specs for the permission push](https://docs.google.com/document/d/1kPeoleBkQuAhuYzr0n5BXE--eUQxyANuvwEV7JUfTfU/edit)

[Swagger for the permission push](https://ega.ebi.ac.uk:8053/ega-permissions/swagger-ui.html#/)

**Comment by jaakkocsc** [comment]
There is now an endpoint which can be used for testing, swagger for it is in [here](https://ega.ebi.ac.uk:8053/ega-permissions/swagger-ui.html#/)

**Comment by Macroz** [comment]
Let's wait for a while for the authentication method to resolve.

**Comment by Macroz** [comment]
I updated the ticket description based on today's coffee call.

**Comment by Macroz** [comment]
Some leftovers were added as new tasks. See https://github.com/CSCfi/rems/issues/2687,  https://github.com/CSCfi/rems/issues/2686 and https://github.com/CSCfi/rems/issues/2684.

**Comment by Macroz** [comment]
Let's merge this after a small 2.20 release.

**Comment by Macroz** [comment]
Merged.
