### ISSUE TITLE
When you want to see your applicant's application history, you see every applicant's application history

### ISSUE THREAD

**Issue by emmakkarttunen** [CSCfi/rems#2470]
You cannot filter just chosen applicant's application history by choosing "Applicant's previous applications" - instead you get every applicant's application history.

This ticket was sent to FinData's bug tracking. Original: https://rt.csc.fi/rt/Ticket/Display.html?id=453393

**Comment by opqdonut** [comment]
Just checking: you mean every member's application history?

**Comment by emmakkarttunen** [comment]
I'm not sure how you define "member". What I think Rosa means is that when she tries to get applicant John Johnson's application history by selecting "Applicant's previous applications" in his applications, she also gets application history from all other applicants in the system. So she cannot filter just John's previous applications. Does that help? 

Rosa said that this used to work fine before.

**Comment by opqdonut** [comment]
Right, thanks for the clarification, I think I see what you mean now.
