### ISSUE TITLE
Tab navigation has bugs focusing on <a> tags 

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2487]
- Looks like it is only a problem for macs
- OS Mac Catalina

TODO:
- add gifs (convert videos)
- add possible solutions

**Comment by Macroz** [comment]
Perhaps it's this
https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html

**Comment by marharyta** [comment]
@Macroz should we add some note about it to readme?
and close the issue?

**Comment by marharyta** [comment]
as this has been currently fixed by the additions to the documentation, I am closing the issue
see [https://github.com/CSCfi/rems/pull/2494](https://github.com/CSCfi/rems/pull/2494)
