### ISSUE TITLE
Accidentally wrong document added to decision 

### ISSUE THREAD

**Issue by emmakkarttunen** [CSCfi/rems#2488]
FinData office worker has accidentally added a wrong document to a decision he has given to a customer. Can the document be removed? 

Application: THL/3353/14.02.00/2020 findata-rems-2020/424
Wrong document: THL_4735

This ticket came to FinData's bug reporting: https://rt.csc.fi/rt/Ticket/Display.html?id=455512

**Comment by Macroz** [comment]
Closing this as the feature ticket is there already.
