### ISSUE TITLE
Ability for handler to redact attachments.

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2491]
Sometimes the wrong attachment gets added (e.g. #2488) and needs to be redacted. We could add an API (and perhaps a UI) that would let the owner redact (i.e. zero the contents of) attachments. Redaction could also add an event to the application events, e.g. "Handler redacted attachment X".

- [x] implement an API to redact an attachment (like the other commands in `api/applications.clj`)
  - [x] clear the attachment contents in DB, possibly in process manager
  - [x] add new event of `attachment-redacted` with optional comment
- [ ] implement action in UI for redacting an attachment similar to review action with checkboxes to filenames
- [x] show event and optional comment for handlers always, and to applicants if redacting an application attachment
  - If the event where the attachment came from is shown to the applicant, then the redaction should be shown too. Otherwise not.
- [x] Show related events could show the event from where the redacted attachment came from.
- [x] Attachment names should be unique (seem to be already e.g. `foo (1).png`, `foo (2).png`)

First PR could be the API with the UI later.

**Comment by Macroz** [comment]
Could be that it should be the handler, in case the handler has added the document.
