### ISSUE TITLE
Bona fide bot UX improvements

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2511]
(split out from #1523)

- [ ] customize email text for decision request (currently it's a generic "Bonafide Bot has requested a decsion from you ...")
  - one option is to just use extra-translations to override the email text for the bonafide rems instance
- [ ] expiry (close) for pending applications

**Comment by meericsc** [comment]
Closing this issue since we have retired Bona Fide REMS, if development continues we can reopen.
