### ISSUE TITLE
Test environment for bona fide

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2528]
deploy REMS with bona-fide-bot configured, and the bona fide push script (#2513) and test the bona fide usecase end-to-end

This is done ad-hoc style to rems-test project in Rahti. Probably good to configure test installation in rems-deploy.
- [ ] configure ad-hoc `rems-bona-fide-test` pod in rems-deploy

**Comment by meericsc** [comment]
Won't do right now
