### ISSUE TITLE
Combine user and profile

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2532]
Use the user icon + name as the link to the user profile as is usual on other sites. Remove the Profile icon and link. This will free up some space.

**Comment by marharyta** [comment]
<img width="423" alt="Screenshot 2021-01-25 at 10 22 36" src="https://user-images.githubusercontent.com/7344718/105679522-40add800-5ef7-11eb-8da3-5c12a020907f.png">

**Comment by marharyta** [comment]
I see two ways to fix that issue:
1. The link to profile should be attached to the "human" icon and "gears" should be made redundant
2. In case if we do have settings, the gear icon can remain and the profile info can go into settings (not my fav option)

**Comment by Macroz** [comment]
There is no need to keep the profile or the gears. Just put the human icon and name as the link to the profile.
