### ISSUE TITLE
Phone number & IP address field types

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2552]
Add two new field types. Split out from #2404

- [x] Backend & schema
- [x] Applicant UI
- [x] Form editor
- [x] manual
- Phone number validations
  - [x] Phone number can only consist of + and numbers (spaces are accepted)
 
- IP address validations
  - [x] IP address should support ipv4 and ipv6
  - [x] Optionally reject private IP addresses (10.x.x.x etc.)
  - [x] link-local probably needs to also be excluded
  - [x] according to @Macroz "we had the discussion in grooming and the result was that ticket (i.e. there is no other validation / outside service because there can't be and but we would consider only public IP addresses so we can invalidate private ones)" 
  - [x] from @jaakkocsc "192.168.x.x
                                        172.16.x.x
                                        10.x.x.x
                                        169.254.1.0 to 169.254.254.255
                                        100.64.0.0 to 100.127.255.255
                                        224.0.0.0 to 224.0.0.255"
<img width="1195" alt="Screenshot 2021-03-25 at 11 12 05" src="https://user-images.githubusercontent.com/7344718/112448343-fad88900-8d5a-11eb-88fe-4d87fe825159.png">

**Comment by marharyta** [comment]
I was actually wondering if we could split the ticket into backend and frontend and I could actually work on the schema a bit?

**Comment by opqdonut** [comment]
As discussed, no need to split the ticket, but the implementation can be in multiple parts.

**Comment by marharyta** [comment]
picking a regex to validate the phone number, which formats we would ideally like to support?
