### ISSUE TITLE
Move up, down and delete buttons of field are not in the header row anymore (they have fallen down lower)

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2563]
Move up, down and delete buttons of field are not in the header row anymore (they have fallen down lower)

- [ ] fix the layout so that the buttons are at the top

![field_buttons](https://user-images.githubusercontent.com/823661/107918264-040f5280-6f72-11eb-84b1-623f302318a6.png)

**Comment by opqdonut** [comment]
This got fixed in #2598 #1899
