### ISSUE TITLE
tweaking of nav logo

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2566]
<img width="711" alt="Screenshot 2021-02-15 at 14 34 10" src="https://user-images.githubusercontent.com/7344718/107947301-e1ddfa80-6f9a-11eb-849b-3bc4ef9e2a15.png">
After adding navbar logo option to the menu for THL biobank here [https://rems-thl-demo.rahtiapp.fi/](https://rems-thl-demo.rahtiapp.fi/) @Macroz had a few suggestions on the design improvement:
- looks kinda small
- I think the quickest thing to do is to remove all the whitespace around the logo in the image because seems like the current styles force some paddings (probably they shouldn't)
- also the styles should be changed so that you can decide the size of the image when doing the theme
- (that should then affect the width/height of the menu without breaking it)

<img width="718" alt="Screenshot 2021-02-15 at 13 37 03" src="https://user-images.githubusercontent.com/7344718/107941780-e6061a00-6f92-11eb-9953-6c8a7d09bbbe.png">
<img width="707" alt="Screenshot 2021-02-15 at 14 21 54" src="https://user-images.githubusercontent.com/7344718/107946068-2ff1fe80-6f99-11eb-9ffb-ba748e3ff448.png">

**Comment by Macroz** [comment]
Let's tweak the logo when/if we have requirements from the users. Closing for now.
