### ISSUE TITLE
categories for attachments

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2571]
Attachments stored in REMS should have a category attached to them (attachment to an application, attachment to a comment, attachment to a decision, etc.). This would make it easier for integrations to pick just certain attachments.

**Comment by opqdonut** [comment]
waiting for a more concrete spec

**Comment by opqdonut** [comment]
#2453 got implemented, but see also #2654

**Comment by opqdonut** [comment]
Let's not do anything more right now.
