### ISSUE TITLE
Change applicant

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2581]
Handler should be able to change the original applicant for a submitted application.
Background: There are cases when an applicant has resigned from his/her position during the application process, and the application is thus left without ownership. A controlled way to tackle the issue would be to allow the handler to change the applicant.

**Comment by opqdonut** [comment]
See also #2244

**Comment by opqdonut** [comment]
We discussed this and came up with two solutions:

A) Implement a "Promote member to applicant" command.

Using this the handler could invite a new member (by email or userid), promote them, and then remove the old applicant (who is now a member.

B) Implement a "Invite applicant by email" command.

Similarly to the invite reviewer, invite decider and invite member actions.

Both approaches make sense, but we decided to _start with option A_.

**Comment by jaakkocsc** [comment]
Tilastokeskus prefers method A.

**Comment by opqdonut** [comment]
#2657 implements option A

**Comment by opqdonut** [comment]
- [ ] email notifications
