### ISSUE TITLE
Figure out a way for REMS users to use custom fonts.

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#2586]
Currently, `theme.edn` allows you to specify a `font-family` style. However, there's no way to add custom web fonts to REMS. We bundle Lato and Roboto Slab into REMS for use in the THL and Findata themes, but that won't help new users of REMS.

**Comment by opqdonut** [comment]
One option would be to allow to specify font URLs in the theme, and to serve the THL & Findata fonts from some place outside REMS, like CSC Allas. Additional REMS users could then serve their own fonts wherever they wish, or even use a public font CDN.

**Comment by Macroz** [comment]
We should allow extra-stylesheets. Then that can contain pointer to any font files anywhere. Also hosting extra static resources makes it possible to locally host extra stuff and have the styles use it.

**Comment by marharyta** [comment]
As we discussed on flowdock, the following approaches were proposed and talked through:
- to continue adding the fonts the way we used to via ```generate-at-font-faces```
- quote from @opqdonut "a "theme option such as font files" is the way to go, but it requires a bit of work for the deployment part. we could maybe just reuse the :theme-static-resources functionality to serve the font files"
- from @Macroz "just adding configurable stuff to generate-at-font-faces is not a good solution. we should rather allow extra CSS files that can contain anything"
- from @jaakkocsc "finally had time to look into this interesting discussion. my five cents: no cdn in rems in default config/style. injecting custom css woudld be good and then it's up to the customer to use whatever method they want in their css. i agree with make that cdns are a huge privacy issue, especially in products like rems."
-

**Comment by marharyta** [comment]
I think it is pretty safe to say we arrived at a conclusion that we should use a custom stylesheet as @Macroz suggested.

**Comment by marharyta** [comment]
The only concern I would be having is:
- do we know whether our users have enough technical literacy to actually write their own stylesheets? @opqdonut @Macroz @jaakkocsc ?

**Comment by opqdonut** [comment]
I think we can assume that. We can always offer an example font-face css file if needed.

**Comment by Macroz** [comment]
Here is a workaround with existing features:
- Prepare a directory from where you will serve static files from. This needs to be deployed with the app (jar). I used the directory `/tmp/static`.
- Add a stylesheet file with any CSS definitions you want to use (could be `@font-face` that could reference the font files in your static directory). I used the name `additional.css`.
```css
body {
  background-color: cyan;
}
```
- Add a small JavaScript file that loads the CSS file through the extra scripts mechanism. I used the name `additional.js`.
```js
var link = document.createElement("link");
link.type = "text/css";
link.rel = "stylesheet";
link.href = "additional.css";
document.head.appendChild(link);
```
- Now add extra configs to the REMS instance like so referencing the JS-file and directory above:
```EDN
 :extra-static-resources "/tmp/static"
 :extra-scripts {:root "/tmp/static" :files ["additional.js"]}
```
- Restart the server! Voilà!

**Comment by marharyta** [comment]
works for me :)

**Comment by Macroz** [comment]
Closing this issue as it has a solution. The more general issue of extra styles has its own issue now.

**Comment by Macroz** [comment]
There is an alternate (easier) solution also in https://github.com/CSCfi/rems/issues/2869 where one can add extra stylesheets directly.
