### ISSUE TITLE
Refactor font definitions: add missing formats of currently available font files and add fallback to available system fonts

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2592]
Make sure that the font files for the supported fonts such as Lato and RobotySlab are supported according with the best practices font face @import statements https://css-tricks.com/snippets/css/using-font-face/

**Comment by opqdonut** [comment]
I think we can safely just use woff2: https://caniuse.com/?search=woff2 . Our current browser support policy is

> REMS is developed and tested with _up-to-date Chrome and Firefox_. 

(See docs/architecture/007-browser-support.md)

**Comment by marharyta** [comment]
https://uxdesign.cc/2020-019-web-fonts-done-right-e21df103205
"we are talking about people in research groups, people who might be using university infra to access the rems website with god knows for how long have not been updated software"

**Comment by Macroz** [comment]
Let's just use WOFF2 if we go here. But consider doing this with #2869 and https://github.com/CSCfi/rems/issues/1467
