### ISSUE TITLE
Categories and/or grouping to the catalog

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2604]
If the catalog grows long it would be a good idea to allow grouping of several catalog items into collapsible groups for easier browsing.
At the same time, categorising catalog items would probably make sense for the basis of collapsible groups.

**Comment by opqdonut** [comment]
Two possibilities:

1. Create a "categories" concept in the administration UI and let owners add categories (including localizations) and pick the order in which the categories are shown on the landing page. When creating a catalogue item you could then pick any number of categories.

2. Implement categories in the "catalogue items" administration page. Let the owner divide the catalogue item list into multiple lists and give the lists names.

Need to check how this meshes with https://www.w3.org/TR/vocab-dcat-3/ 

For context, this is what the list of Statistics Finland's datasets looks like now: https://taika.stat.fi/en/index

**Comment by opqdonut** [comment]
If you change the form of a catalogue item (i.e. copy the catalogue item), it should stay in the same category.

**Comment by opqdonut** [comment]
Discussed in planning meeting, will probably go with option 1.

**Comment by marharyta** [comment]
Agree that we should go with option 1.

**Comment by marharyta** [comment]
@Macroz So, as for the data structure, I assume categories will be similar to resources in a way that they have 
```
:organization, :owneruserid, :modifieruserid
```

**Comment by Macroz** [comment]
> @Macroz So, as for the data structure, I assume categories will be similar to resources in a way that they have
> 
> ```
> :organization, :owneruserid, :modifieruserid
> ```

Do we need owneruserid?
