### ISSUE TITLE
Allow non-handler/owner users to query for their own permissions at the /permissions endpoint

### ISSUE THREAD

**Issue by katpavlova** [CSCfi/rems#2631]
### Feature Request
As a developer of a microservices architecture that relies on REMS for managing DAC-granted dataset-level data access permissions, I want to fetch a user's GA4GH Visa from the `/permissions` endpoint and use it to make authorization decisions in other microservices.

I am able to fetch the user's entitlements in REMS at the `/entitlements` endpoint using only a `x-rems-api-key` and the user's `x-rems-user-id` for authorization, but the `/permissions` endpoint additionally requires the user id of someone with a handler or owner role. This does not lend itself well to use in automated authorization workflows. Currently, we are needing to initialize a generic `owner` REMS user (whose ID is an environment variable) as a workaround.

### Acceptance Criteria
- [ ] Can fetch any user's permissions from the `/permissions` endpoint, such that:
    - [ ] The combination of a `x-rems-api-key` and *this user's* `x-rems-user-id` is sufficient for authorization.

**Comment by opqdonut** [comment]
Thanks! That's a very reasonable request. I can't see any reason not to implement this. We'll prioritise this request latest next Monday.

**Comment by opqdonut** [comment]
implemented, available in the `master` branch and in the next release (v2.18)
