### ISSUE TITLE
Form behaviour ideas

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2639]
Problems with the current (applicant) UX:

1. You don't know if your inputs (e.g. ip address) are valid before pressing Save, and then you need to fix all of these errors before REMS saves your work
  - Possible solution: Show validation errors to the user, but perform the save anyway. (Show errors in yellow?)
2. You need to perform an action (save/submit) to see the validation errors
  - Possible solution: Validate when user stops typing / leaves field
  - Questions:
    - What about partially filled in forms? It would be best to not show validation errors for fields that haven't been edited yet.
    - What if a user navigates away from the application and back? Do they see the validation errors, or perhaps just the state of the application as-is before they write something.
    - What to do with required fields? Should they all turn red immediately or only upon save? Or only upon submit?
  - Idea – three states for application fields:
    - untouched (not filled in at all)
    - edited but not valid (can save, can't submit)
    - filled in and completely valid (can submit)
3. You need to perform an action (save) to save your work.
  - Arguably not a problem, users are used to Save buttons?
  - Possible solution: Autosave (cache) into browser localstorage
    - With an explicit _save_ button. We wouldn't call caching "saving" to the user.
  - Possible solution: Autosave into REMS db
    - Problems:
      - Depends on 1
      - Lots of events generated to the REMS db
      
Plan:
- [x] Turn this into an ADR
- [ ] Make save succeed even with validation errors. Show validation errors in yellow (instead of red)
- What next?

**Comment by Macroz** [comment]
NB: the first one is a bug #2766. The options are discussed in the ADR so we can close this issue.
