### ISSUE TITLE
Allow inviting handlers via email

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2650]
Current process for defining a data access committee, aka handlers in REMS, does not allow automatic provision of handlers easily; the provisor must know userid's of the handlers.

For automated provision it should be possible to invite handlers to a workflow by using their email addresses similar to inviting members to an application.

This also links to https://github.com/CSCfi/rems/issues/2244

**Comment by opqdonut** [comment]
Only need to invite handlers for workflows, not for individual applications.

**Comment by jaakkocsc** [comment]
Use case is like this:

A researcher from a university publishes a dataset to CSC services. Upon publishing certain metadata needs to be defined, and data access committee is one such information. Typically the DAC consists of several university's senior staff members and the publisher enters their names and email addresses into the metadata. Each and every dataset may or may not have same DAC.

An automatic process in the CSC service parses the metadata, and populates REMS with sufficient information to create a catalog item for the dataset. A workflow should also be created but at this point there's only the email address(es) of the DAC member(s) aka handler(s).

**Comment by opqdonut** [comment]
Discussed some approaches:

A) Add an `invited-handlers` field to the workflow schema. Inviting a handler adds a record here and sends an email. The invitation can be accepted via a link like `rems/accept-invitation/handler/<workflow-id>/<invitation-token>`. Accessing the link will then perform an update of the workflow, which adds the user account as a handler.

B) Similar to A, but track invitations in a separate table. (Kind of similar to the outbox table.) This will make it easier to support various additional types of invitations later. Will also make it simpler to support viewing all outstanding invitations, and resending or canceling some of them. However, displaying the invited handlers when viewing a workflow will be slightly more work to implement.

C) Implement the approach from ADR 014 (TODO: link) and have separate internal and external user ids in REMS. When a workflow is edited, and a handler is invited by email, REMS creates a virtual user with just an internal id, and assigns them as a handler. An invitation email is sent to the invitee, and when they log in their external user id is associated with this internal id and they immediately are a handler of the workflow.

Problems:
- What about multiple invitations to the same email? Might need to merge users.

**Comment by opqdonut** [comment]
Let's start with implementing B.

**Comment by opqdonut** [comment]
@jaakkocsc says it's enough to start with an API-only implementation.
