### ISSUE TITLE
Implement vertical navigation for administration menu

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2662]
As I started working on the #2604 ticket I noticed that the administration menu is becoming very packed. I suggest implementing a vertical side menu for the administration features.
<img width="1289" alt="Screenshot 2021-05-10 at 10 47 56" src="https://user-images.githubusercontent.com/7344718/117624076-300b3000-b17d-11eb-909f-a0159fb284af.png">

Possible solutions: [https://freefrontend.com/bootstrap-sidebars/](https://freefrontend.com/bootstrap-sidebars/)
<img width="720" alt="Screenshot 2021-05-10 at 10 48 14" src="https://user-images.githubusercontent.com/7344718/117624119-3bf6f200-b17d-11eb-99e5-12d5ece91549.png">

**Comment by opqdonut** [comment]
... or figure out some other way of fitting more entries now that we've run out of horizontal space.

**Comment by Macroz** [comment]
One possibility is just wrap the new items to the next row. That'd be close to what it is now (i.e. links are always visible) and responsive.

**Comment by Macroz** [comment]
Duplicate with #2699

**Comment by Macroz** [comment]
There is no need for this now, but we can reconsider this if we do a UI refresh that is based on UX design or while doing any UI refresh.
