### ISSUE TITLE
Expiry date for drafts

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2665]
In order to

- prevent drafts piling up
- mitigate for submitting applications long since expired forms

there should be a mechanism to expire drafts. It could be a feature of an workflow.

Feature must not have an effect on submitted applications or returned applications.

**Comment by opqdonut** [comment]
Previously: #2436 #2145 #1524

**Comment by opqdonut** [comment]
I think we've talked in the past about moving from enabled/disable/archived to a more granular model with checkboxes like:
- visible in catalogue?
- can create new draft?
- can submit old draft?
- can resubmit returned application?

**Comment by opqdonut** [comment]
Could also consider a warning like "This catalogue item has been disabled for 6 months, please consider creating a new application."

**Comment by jaakkocsc** [comment]
Decision: we actually delete the events from the database for applications that have not been submitted after a certain set time limit. Check other tables too, like attachments.

**Comment by aatkin** [comment]
We can create a scheduler to delete drafts periodically, and as discussed today, this scheduler should be implemented in REMS

**Comment by aatkin** [comment]
reopening, discovered potential issue when `defstate` returns nil

```
:type clojure.lang.ExceptionInfo
   :message "could not stop [#'rems.application.eraser/expired-application-poller] due to"
```

**Comment by aatkin** [comment]
demo notes:

- add documentation about config feature (duplicate) to `configuration.md`
