### ISSUE TITLE
Wider tables in administration view

### ISSUE THREAD

**Issue by marharyta** [CSCfi/rems#2699]
**Description of the issue:** 

When logged in with administration priviledges, ie as a handler, the Administration view looks like this:
<img width="1334" alt="Screenshot 2021-07-14 at 13 31 57" src="https://user-images.githubusercontent.com/7344718/125607910-91aeb5a3-c7d9-42d9-a360-46bb214e8437.png">

**Problem:**
Links to Administration panel are too tight, very hard to read and are invisible from any other page (you have to be on the administration page to see them)

**Proposal:**

Create a multi-level menu to showcase administration view links when not on the administration page + create vertical menu for the administration page settings

ex: [https://bootstrap-menu.com/demos/multilevel.html](https://bootstrap-menu.com/demos/multilevel.html)

**Constraints:** 
The form editor is fullscreen, might want to think about it :)

**Comment by Macroz** [comment]
Page widening is issue https://github.com/CSCfi/rems/issues/501, closing this duplicate.
