### ISSUE TITLE
Can't change resources

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#2702]
Possible bug to hunt:

There's an application with two resources in it, and for some reason it is impossible for the handler to remove one of them.

**Comment by Macroz** [comment]
Is this related? https://github.com/CSCfi/rems/issues/2693

**Comment by jaakkocsc** [comment]
Yes, it is. But the client reports that even if the resources are activated again the problem persists.

**Comment by Macroz** [comment]
Yes it has nothing to do with the state actually. The original description is not as useful as the instructions to duplicate the problem.
