### ISSUE TITLE
Configuration flag for disabling bundling / the shopping basket

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2720]
Some REMS uses are so simple that there is no need for the "shopping cart" function. We could instead have a direct apply link from the catalogue. This also means there is no bundling of multiple items to one applications.

- [x] config flag to disable shopping cart (or `:enable-cart` with default of `true`)
- [x] hide shopping cart
- [x] replace add / remove buttons with apply buttons
- [ ] optional: browser test (difficult to fake config at the moment)
- [ ] optional: consider disabling something from the API or force applications submitted through it to also contain at most one item

**Comment by jaakkocsc** [comment]
config flag would probably be better like `:enable-multiple-resources-in-application` and defaults to true
