### ISSUE TITLE
Organization owners could be allowed to edit their own organization owners

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2828]
Currently we don't allow organization owners to edit organization ownership. The owner role is the only one allowed to do so. This could be changed so that the organization owner can edit the owners of the organizations they own. This would be slightly better alignment with the delegated ownership model.

**Comment by Macroz** [comment]
See also #2850.

**Comment by aatkin** [comment]
User should not be able to edit organization if they are not this organization's owner.
