### ISSUE TITLE
Add authenticated SMTP for notification emails

### ISSUE THREAD

**Issue by andrewpatto** [CSCfi/rems#2895]
We are setting up an instance of REMS in AWS - and would like to use the AWS accounts' SES for sending emails.

However, to do this requires authenticated/tls outgoing SMTP.

Is there a way to configure this currently in REMS - it didn't look like the config for SMTP had enough settings - but possibly there is a passthrough mode for the eventual smtp client?

I see that the clojure postal library (which I believe is used) *does* support a variety of authed emails

```
postal.core> (send-message {:user "AKIAIDTP........" :pass "AikCFhx1P......."
                            :host "email-smtp.us-east-1.amazonaws.com"
                            :port 587}
               {:from "me@draines.com" :to "me@draines.com"
                :subject "Test from Amazon SES" :body "Test!!!11"})
{:error :SUCCESS, :code 0, :message "messages sent"}
postal.core>
```

so perhaps this might be just enough to allow the `:user` and `:pass` fields to be passed through from a config setting

**Comment by Macroz** [comment]
Hey! Sounds like a good additional feature. We haven't had this requirement yet, so failed to consider it in advance. We'll add the issue to our backlog.

**Comment by Macroz** [comment]
I've implemented a solution that allows passing through any arguments to postal. I tested it quickly in our integration tests. Would be helpful if you can confirm that it works @andrewpatto.

**Comment by andrewpatto** [comment]
Thanks - am doing some testing now.

When put directly into the config.edn - I could get the SMTP auth passthrough to work.

When using env variables (which is how I set a lot of my other settings such as OIDC secrets etc)

```
SMTP__HOST: "email-smtp.ap-southeast-2.amazonaws.com",
SMTP__PORT: "587",
SMTP__USER: "AKIA...",
SMTP__PASS: "BG...",
MAIL_FROM: "rems@host.com",
SMTP_DEBUG: "true"
```

It is saying it is missing the smtp host and port (hence it does a fake email send).

Have I got the env variable technique wrong for nested settings (distinctly possible!)?

**Comment by Macroz** [comment]
> It is saying it is missing the smtp host and port (hence it does a fake email send).
> 
> Have I got the env variable technique wrong for nested settings (distinctly possible!)?

I'll check it out tomorrow!

**Comment by Macroz** [comment]
Since `:smtp` is empty I don't think it's able to be overridden so easily. Theoretically one could have it set in the config, and then override in the env, but I think I can get it to work with this fix https://github.com/CSCfi/rems/pull/2918

**Comment by andrewpatto** [comment]
Thanks for that - I have done the 'set in config and then overwrite via env' and that works. Anyhow, is orthogonal to the auth SMTP feature which is definitely working now. So this PR/issue can be closed. Thanks for the work on this.
