### ISSUE TITLE
More configurable logout

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#2916]
Besides not documented (see #2915), we should improve the configurability of the logout. Some IdP can do the logout only if we redirect them to a logout URL (and not always to REMS front-page).

- [x] `:oidc-logout-redirect-url` where to redirect the user
- [x] maybe include configuration that decides whether to do the revocation POST at all

**Comment by mzha999** [comment]
Thanks Macroz, it would be great if you could create a configurable logout url

**Comment by Macroz** [comment]
@mzha999 if you want you can test the solution in this PR https://github.com/CSCfi/rems/pull/2923
