### ISSUE TITLE
Sort the licenses by the name to have a more stable order.

### ISSUE THREAD

**Issue by aatkin** [CSCfi/rems#2979]
Application license list is slightly random in order. We should sort the licenses by the title (in the UI).

- [ ] licenses are sorted alphabetically by the shown title

**Comment by aatkin** [comment]
Converted into issue - could use extra information such as where the sorting should happen

**Comment by Macroz** [comment]
> Converted into issue - could use extra information such as where the sorting should happen

So far all the sorting happens in the client (that knows the language which determines the sorted text).
