### ISSUE TITLE
Align category API with other APIs

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/rems#3036]
**Is your feature request related to a problem? Please describe.**
The different APIs follow a distinct pattern `POST /api/{item}/create`:
```
POST /api/applications/create
POST /api/licenses/create
POST /api/forms/create
POST /api/resources/create
POST /api/catalogue-items/create
```
We are programmatically creating items using the pattern `/api/{item}/create` and would like to be able to use the same pattern with `categories` as well, but at the moment its API is slightly different from the others.

**Describe the solution you'd like**
Update `categories` API to follow the same convention as other APIs.
```
POST /api/categories/create
```
instead of
```
POST /api/categories
```

The following is not important to us, but the same can be seen in updating items:
```
PUT /api/categories
```
vs
```
PUT /api/{items}/edit
```

**Additional context**
`GET` already works the same for all items. :+1:
```
GET /api/{item}
GET /api/{item}/{item-id}
```

**Comment by Macroz** [comment]
Looks good. A consistent API is desireable.

**Comment by aatkin** [comment]
We could also change organizations API `PUT /edit` into `POST /edit` for consistency.

**Comment by Macroz** [comment]
@teemukataja This is now merged to master, if you want to test it already. It should appear in the next release in a while.
