### ISSUE TITLE
PDF missing information

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/rems#3108]
Some information in the application gets lost in pdf saving.

**Comment by jaakkocsc** [comment]
![16105734](https://user-images.githubusercontent.com/10267750/213099079-141fd905-c0fe-400d-82a0-169bd97f3a9f.png)
![16105735](https://user-images.githubusercontent.com/10267750/213099115-14f9e96b-c093-4d87-91dc-df07df1e8f2c.png)

**Comment by Macroz** [comment]
The mismatch can be from not pressing save before printing the PDF. The PDF is generated based on what was already saved. This is something we should probably change, although autosave would make this quite redundant.

**Comment by meericsc** [comment]
Autosave will fix this, so let's not implement this for now.
