### ISSUE TITLE
Organisation information from authentication

### ISSUE THREAD

**Issue by meericsc** [CSCfi/rems#3133]
Get Big Picture organisation information from LS AAI. If the person logging in is part of a BP organisation allow log in. If not, error-page with an explanation and instructions on how to continue.  
Configuration option so this can be used for other organisations too.

**Comment by Macroz** [comment]
The instructions for use:
- update `rems.jar` to a new version with the changes
- copy the plugin-files from the [plugins-directory](https://github.com/CSCfi/rems/tree/master/resources/plugins)
- configure REMS with something like

```clj
 :plugins [{:id :plugin/AARC-G069-group-split
            :filename "AARC-G069-group-split.md"
            :attribute-name "eduperson_entitlement"
            :trusted-authorities ["perun.aai.lifescience-ri.eu"]}

           {:id :plugin/validate-group-membership
            :filename "validate-group-membership.md"
            :attribute-name "groups"
            :valid-groups ["VO1"]
            :error-key :t.login.errors/group}]

 :extension-points {:extension-point/transform-user-data [:plugin/AARC-G069-group-split]
 :extension-point/validate-user-data [:plugin/validate-group-membership]}}
```
