### ISSUE TITLE
Refactor autoapprove

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#314]
Autoapprove doesn't need to be a loop: the only situation where autoapprove rounds are useful is having exactly 1 autoapprove round.

We should refactor the code so that when the application is submitted, we check _once_ `is-workflow-eligibile-for-autoapprove?` and then autoapprove.

We could also change the representation for a autoapprove workflow to be one with no rounds. This would get rid of the no-approvers round type.

**Comment by okahilak** [comment]
Obsolete.
