### ISSUE TITLE
hooks no longer seem to work as doc'ed

### ISSUE THREAD

**Issue by delocalizer** [CSCfi/rems#3351]
**Describe the bug or behavior**
I'm trying to implement a hook in `js` as described here [hooks.md](https://github.com/CSCfi/rems/blob/master/docs/hooks.md#hooks)

**To Reproduce**
1. Create the hook file `foo.js`
2. Reference it in config via `:extra-scripts` 
3. Start services, open the JS console in the browser, and perform any UI action in REMS
4. `foo.js` throws an error stating that `rems.hooks` is undefined:

![image of JS console showing a red cross with text Uncaught TypeError: Cannot read properties of undefined (reading 'hooks)](https://github.com/user-attachments/assets/76d0b749-3df8-42ac-bc7b-a3feea6c5993)

**Expected behavior**
This used to work, prior to d436777, which removed the inline JS initialization of the hooks.

If I revert back to 2f3321e and build, the exact hook example file in the [documentation](https://github.com/CSCfi/rems/blob/master/docs/hooks.md#hooks) works as expected.
So I'm not sure if this is a bug in the documentation because hooks actually work a different way now, or a bug in the current hook implementation.

**Environment**
 - Version of REMS: v2.37
 - OS: Fedora Linux fc40
 - Browser: Chrome 131.0.6778.33

**Comment by delocalizer** [comment]
![Screenshot from 2024-08-15 09-33-58](https://github.com/user-attachments/assets/006e56e7-132d-4bcb-91cb-ab6d35efca3c)

**Comment by delocalizer** [comment]
Screenshot appears borked due to a github issue. I'll upload again when it's resolved, but the alt text is:
'image of JS console showing a red cross with text `Uncaught TypeError: Cannot read properties of undefined (reading 'hooks')` on the execution of:
```js
window.rems.hooks.navigate = function (path) {
    // info
    console.log("I navigate to " + path);
};
```

**Comment by Macroz** [comment]
Thanks for the report. I'll have a look!

**Comment by Macroz** [comment]
I think the problem is with the timing. The extra scripts are inserted now in the head before `rems.hooks` namespace is loaded in the app content. The new initialization will override anything you set in the extra scripts.

I think you can for now just delay setting of the hooks until after page is loaded (even `setTimeout` should work).

But I will make it so that the initialization doesn't override anything. I'll also add a test for this so it won't break.

**Comment by Macroz** [comment]
I had to rename the location as `window.rems_hooks`, but I think the merged solution now works. Let me know if this fixes it for you or if some problem still remains!

**Comment by delocalizer** [comment]
Great, thank you — yes this fixed the issue.
