### ISSUE TITLE
public-url with a path component behaves oddly

### ISSUE THREAD

**Issue by delocalizer** [CSCfi/rems#3356]
**Describe the bug or behavior**
I want to run REMS under a base URL e.g. to have the whole application under `https://my.domain/rems/`. I've tried to test that on my dev machine by setting `:public-url "http://localhost:3000/rems/"` in `config.edn` but this does not behave as I expected:
* Some of the application links (e.g. landing page and login button target) are still presented at `http://localhost:3000/`
* If I click on `http://localhost:3000/fake-login` and select the Alice user, I get redirected to `http://localhost:3000/rems/redirect` which is a page with an empty body: 

![Screenshot from 2024-11-23 17-49-13](https://github.com/user-attachments/assets/0604b4b6-7629-4fd8-90fd-b76494c91934)

It seems like some but not all paths respect the `public-url` with a path component. Is this not the correct way to run REMS under a base URL?

(Aside: the motivation for this is to use path-based routing to run REMS under the same domain as other related services)

**To Reproduce**
1. Set `:public-url "http://localhost:3000/rems/" in config
2. Start services and navigate around

**Expected behavior**
* I expect all application paths to become relative to the last `/` in `public-url`, i.e. all services to be at `http://localhost:3000/rems/...`
* I expect when I click on the Alice user on the fake login page to be redirected to the catalogue page `http://localhost:3000/rems/catalogue`

**Environment**
 - Version of REMS 8fc45cf
 - OS: Linux (Fedora 40)
 - Browser: Chrome 132.0.6834.15

**Comment by delocalizer** [comment]
I think this is probably me misunderstanding the scope of `public-url` so it's more of a feature request to support hosting at a non-root URL. I will first try to implement my requirement outside of REMS using e.g. a reverse proxy.

**Comment by Macroz** [comment]
Hey,

All current installations have some kind of a gateway or proxy in front of REMS, so this has not been required so far. Definitely it could be useful, and could be made to work with some effort.

A separate but related issue is that the "fake auth" is not intended for production so it may not have all necessary features.
