### ISSUE TITLE
fix closed resource-license handling

### ISSUE THREAD

**Issue by ghost** [CSCfi/rems#391]
- [x] should not show resource licenses that have been closed for new applications (these have an end date)
- [x] new resource licenses should not be shown for old applications
- [x] closed resource licenses should be shown for legacy applications
- [x] add to test-data licenses that used to be in a resource
- [x] fix bug where application could be sent with disabled catalogue item (test data already exists)
- [x] add tests to workflow license expiration

**Comment by Macroz** [comment]
The tests check the `db/get-licenses` which in turn normally returns a union of resource and workflow licenses. Therefore both kinds of licenses get the same active logic treatment and don't need duplicated tests.
