### ISSUE TITLE
Make site layout wider on laptops/desktops screens

### ISSUE THREAD

**Issue by ghost** [CSCfi/rems#501]
For a quick improvement
- [x] widen admin page containers
   - could make tables use only as much space as needed (as narrow as possible)
   - alternatively could have maximum size for table around 2500px wide (not super wide on widescreens)
- [x] admin menu must be set to use `justify-content: center` and approximately `gap: 2rem`

Split
- ~[ ] widen the rest of the site containers, when doing a UI refresh~

**Comment by Macroz** [comment]
From a note:
> Try using the Bootstrap fluid-container to allow for a wider actions bar on extra wide screens. It's possible this won't work but in case it doesn't then let's try using flexbox or CSS grid for the top level.

We should fix this issue once we do a UI refresh.
