### ISSUE TITLE
roadmap for REMS2?

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#523]
Dear REMS teams,

We've got a REMS2 installation up and running but a few things still to be ready.

would you mind sharing with us your roadmap?

thank you very much

**Comment by tjalkane** [comment]
Now that our MVP is ready we are concentrating on the horizontal growth of features. The focus is especially on making administrative and reporting functionalities better and easier for non-technical people. You can have a look at the milestones page (https://github.com/CSCfi/rems/milestones) to check the goals we have committed to achieve in short term.

If you feel REMS is missing something, please let us know so we can take the feedback into consideration for our next milestone planning session.

**Comment by Masber** [comment]
thank you very much @tjalkane for this update.
apologise my ignorance, I can see 2 milestones (LBR release and demo week 20) what does LBR means?

**Comment by tjalkane** [comment]
More milestones will be made public as we plan our releases. 

LBR stands for Language Bank Rights and it's one of the instances running previous version of REMS in production. Researchers can use it to apply for rights to use corpora and other language resources.
