### ISSUE TITLE
How can I add new items to the catalog list?

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#533]
Dear REMS team,

I have installed REMS with test data, I can see the applications, users, actions, etc. However I can't add new resources to the catalog.

How could I add new catalog items?

thank you very much

**Comment by tjalkane** [comment]
Unfortunately at the moment there is no UI for doing this. However, we do have a task for implementing one: #483.
To add a new catalogue item consider one of these options:

1. Connect to the database and add them manually
SQL queries located at `resources/sql/queries.sql` will provide help with this

2. Calling functions in REPL (`lein repl`)
Example code snippets for `lein run test-data` target can be found from `src/clj/rems/db/test_data.clj`.

Hope you found this answer helpful.
