### ISSUE TITLE
add support for multiple saml2 login endpoints on the front page

### ISSUE THREAD

**Issue by tjalkane** [CSCfi/rems#553]
- [x] multiple configurable logins and endpoints

**Comment by mmatthiesencsc** [comment]
If possible keep the old system, where there was one DS. Not all endusers understand what Haka vs. eduGAIN is. When is the DS coming? I would like to promote LBR outside of Finland.

**Comment by tjalkane** [comment]
Implemented alternative login option as a link in #586
