### ISSUE TITLE
Add eduPersonAffiliation attribute to Actions pane

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#566]
Below Application > Applicant, eg. above schacHomeOrganization

**Comment by Macroz** [comment]
Hi,

Can you please clarify that do you wish to arrange the applicant attributes in a specific different order?

**Comment by mmatthiesencsc** [comment]
Hi, sorry for the delay, I almost missed this one. What I mean is that I would like to see the value of the Shibboleth eduPersonAffiliation attribute shown (if present). Alongside cn, mail, eppn, etc. This attribute is valuable to determine the status of a user and helps detect obvious fraud (e.g. if a student pretents to be a professor).

**Comment by Macroz** [comment]
Looks like `eduPersonAffliation` attribute is shown under the name `unscoped-affiliation` but we can try to alter the mappings so that you also get the `eduPersonAflliation` which describes it better. This would be something that is updated when we next deploy a new version and updated to the users as they login.

**Comment by Macroz** [comment]
This is the mapping that should be deployed. I'm unable to check it myself, so we need to find a CSC person who better knows how to check the available attributes and configuration.

```
    <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.9" id="affiliation">
        <AttributeDecoder xsi:type="ScopedAttributeDecoder" caseSensitive="false"/>
    </Attribute>
    <Attribute name="urn:mace:dir:attribute-def:eduPersonScopedAffiliation" id="affiliation">
        <AttributeDecoder xsi:type="ScopedAttributeDecoder" caseSensitive="false"/>
    </Attribute>

    <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.1" id="unscoped-affiliation">
        <AttributeDecoder xsi:type="StringAttributeDecoder" caseSensitive="false"/>
    </Attribute>
    <Attribute name="urn:mace:dir:attribute-def:eduPersonAffiliation" id="unscoped-affiliation">
        <AttributeDecoder xsi:type="StringAttributeDecoder" caseSensitive="false"/>
    </Attribute>
```

**Comment by mmatthiesencsc** [comment]
Hi Markku,
just to make sure, have you added this already? This in fact can be tested on a pre-production/staging machine if you spoof your local machine (best use a VM) into thinking it works on the production rems. In case of lbr.csc.fi just point lbr.csc.fi to the IP of the staging machine. Since Shibboleth works in the browser, it will log you in on your local machine.

**Comment by mmatthiesencsc** [comment]
This is apparently not implemented in the latest update. It should not be hard, it is just an attribute like any other.

**Comment by opqdonut** [comment]
We'll get back to this after switching to AAI authentication #1234

**Comment by mmatthiesencsc** [comment]
eduPersonAffiliation is still not supported in LBR as of today. It wasn't a show stopper 1,5 years ago and still is not, but it really does impact and improve decision making in corner cases.

**Comment by meericsc** [comment]
It is currently possible to configure extra attributes in the rems, see https://github.com/CSCfi/rems/blob/6878f4c37a862f07853058976a119eb51a1fca6f/resources/config-defaults.edn#L93 so I'll close this issue.
If you have more questions about this, please contact us.
