### ISSUE TITLE
vTHL2: Adding members to an application by applicant

### ISSUE THREAD

**Issue by ghost** [CSCfi/rems#609]
Note: application progress is not dependent on additional members' actions. Only entitlements are.
See also #653 and #870.

- [x] field for inviting members to application by email address and name
- ~if the member doesn't have a REMS user account, send an email invitation for joining~ (moved to #652)
- [x] when coming through the join link (with appropriate secret challenge code) allows your new user to be linked to the application

**Comment by opqdonut** [comment]
split this into #652 and #653

**Comment by opqdonut** [comment]
backend done

**Comment by opqdonut** [comment]
postponed until after dynamic workflow
