### ISSUE TITLE
Feature request: edit catalog item

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#614]
***** New feature request *****

We found the possibility to create new catalog items quite useful, however we miss the option to edit those items by the owner.

Is there a possibility to add the possibility to add an edit button in the administration page that lists the application items for editing?

thank you very much

**Comment by tjalkane** [comment]
In REMS catalogue items are a concept that consists of a workflow, an application form and a resource. There will be an option to create customizable forms, resources and workflows. As for editing already existing catalogue items, we recommend disabling and archiving the old versions and creating new catalogue items with the necessary changes. We might add possibility to edit aspects of existing catalogue items that do not play an important role in the approval process (such as the name of the title of the application form or round approvers).
