### ISSUE TITLE
add/edit/delete and list "terms and conditions" while creating a catalog item

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#615]
***** New feature request *****

Administration --> Create catalog item does not list the tems and conditions assigned to it. It would be nice to have this feature and the possibility to add/edit/delete the terms and condition items linked to a specific catalog item.

**Comment by tjalkane** [comment]
Recently we added the option to create new resources to the administration page. There you can also create new terms and conditions that can be attached to new resources. When this resource is added to a catalogue item, the terms and conditions can be seen when applying for the resource. In the future it will also be possible to attach terms and conditions to specific workflows and application forms.
