### ISSUE TITLE
REMS workflows

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#616]
Dear REMS team,

Is the REMS backend flexible enough to add aditional workflow?

An example would be to create a type of workflow for an application that needs to be approved by 3 different people.

thank you very much

**Comment by tjalkane** [comment]
We are in the process of adding custom workflow creation to the administratio page, please see https://github.com/CSCfi/rems/issues/582. Approval by 3 different people can then be implemented in 2 ways:
1. Creating a workflow with 3 rounds each with different approvals. Here the process will be stuck until that rounds approver has reacted.
2. Workflow round with 3 parallel approvers. Here you have the options to set how many approvers need to approve the request before it continues to the next round.
