### ISSUE TITLE
LBR: REMS should not accept users lacking mail attribute

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#617]
See https://lbr.csc.fi/#/application/744

The mail attribute is empty or shifted to the name attribute. In any case I suspect the user has not got confirmation of acceptance.

**Comment by mmatthiesencsc** [comment]
Expected behaviour: the mail field is always filled. The Name field should be substituted with eppn, if missing.

**Comment by Koura** [comment]
Pr #678 adds fallback to eppn if name is missing. There was a subtle bug that also caused mail field to not be shown in UI, but backend should have handled that properly in case the user had an email attribute.
