### ISSUE TITLE
Provide API to access items with their resource ID (eg URN)

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#634]
I was sure I had reported this already here, but it has been burried in a mail. so here it is again:

>> "Resource IDs need to be part of Apply link"
>> 
>> LBR3 (the present lbr.csc.fi) does not use the resource IDs used in LBR2 (the
>> previous incarnation). This is a massive problem and needs to be fixed. The
>> resource IDs are URN PIDs for a reason, so that the resources can be identified
>> accross services. Take for example: http://urn.fi/urn:nbn:fi:lb-2016112317 If
>> you dont't have access rights you are encouraged to apply via REMS, the link
>> refers to the old version:
>> https://lbr.csc.fi/web/guest/catalogue?domain=LBR&resource=urn:nbn:fi:lb-201403268&target=application
>> 
>> It is very important that we can use a parameter like
>> "resource=urn:nbn:fi:lb-201403268" which contains the resource ID, here a URN.

**Comment by mmatthiesencsc** [comment]
We currently have a workaround in place that manually maps the resourceIDs to database IDs, but that is only a short term solution.

**Comment by luontola** [comment]
We'll add support for links such as `http://rems/#/application?resource=urn:nbn:fi:lb-2016112317` which will open the application for that resource, assuming there is exactly one catalogue item for that resource. Will that work for you?

**Comment by luontola** [comment]
Or maybe the link will be something like `http://rems/api/go-to-application?resource=urn:nbn:fi:lb-2016112317` which will redirect to the application page. That way the external system will not be coupled to the page structure in REMS.

**Comment by mmatthiesencsc** [comment]
Hei, kysyms meni ohi, pahoittelut. Mutta molemmat vaihtoehdot käyvät.
