### ISSUE TITLE
api for adding users

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#650]
- [x] userid, userattrs (minimum set: mail, eppn, name)
- [x] only allowed for owner

**Comment by opqdonut** [comment]
endpoint returns garbage (`[1]`), document/fix

**Comment by Koura** [comment]
> endpoint returns garbage (`[1]`), document/fix

Seems to be a bigger problem as workflow, form and resource api endpoints at least don't have return type documentation in their APIs.

**Comment by luontola** [comment]
Maybe we can write a test which checks that all return types are documented.
