### ISSUE TITLE
vTHL2: sending emails based on events

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#652]
A job that reads application events and sends emails based on them. See [docs/architecture/002-event-side-effects.md](docs/architecture/002-event-side-effects.md)

- [x] email to applicant when application is approved / rejected
- [x] email to applicant when application is closed
- [x] email to commenter/decider when comment/decision is requestd
- [x] email to handler when comment/decision arrives
- [x] same emails to additional members as to applicant
- [x] invitation emails for invited members

**Comment by cscwooller** [comment]
Make sure following emails are sent for both dynamic and "old" workflow

To applicant:
- [ ] application has been approved
- [ ] application has been rejected

To approver:
- [ ] Upon approval request
