### ISSUE TITLE
v2.3: nimi ja mail eivät näy otsikkona

### ISSUE THREAD

**Issue by mmatthiesencsc** [CSCfi/rems#661]
![lbr-bug](https://user-images.githubusercontent.com/8044507/44855467-c4563280-ac73-11e8-97d1-7403cd50bbc1.JPG)

Hei,

Hakemuksessa https://lbr.csc.fi/#/application/766
Nimi ja sähköposti -kentät ovat tyhjiä, vaikka atriibuutit näkyvät oikein.

Toivottu tilanne: Nimi ja sähköposti olisivat täytettynä.

**Comment by Macroz** [comment]
Tämä on korjattu aiemmin PR #678.
