### ISSUE TITLE
form validation not consistent across the web app

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#669]
** CHANGE REQUEST ***
severity: very low

Thsi is not a critical issue but some forms are validated against blur or change events while other through submit events.

It would be nice to have a consistent way of validation across the whole application.

thank you

**Comment by Macroz** [comment]
Hi,

Please, can you specify which field do you mean that is on blur validated? Thanks.

**Comment by hukka** [comment]
Spring cleaning
