### ISSUE TITLE
reviewer can't complete/finish the review round

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#670]
** CHANGE REQUEST ***
severity: high

while testing v2.3 I reliased that reviewers can't complete the round.

If the current application round is of type "review" then the reviewer will see the application listed but there is no way to do any actions on the review.

How to reproduce:

Prerequisites:
having an application in place with current round as "review round"

login a reviewer --> go to ACTIONS --> OPENS REVIEW and click VIEW --> the new form does not give an option to finish/process the round.

What is expected:

Reviewer to be able to complete the round

thank you

**Comment by Masber** [comment]
thank you for your message and sorry for my late response,

I am not familiar with the "3rd party review functionality" how should I use this functinality?

thank you

**Comment by Koura** [comment]
During an approval round, there is an action called 'request review' available for approvers. With that functionality one can select persons for review and those selected will then be able to submit a review during that round. The 3rd-party review will not stall the application so the approver can still handle the application even if all of the reviewers don't submit their reviews. Also the reviewers will not be able to submit reviews anymore if the application has progressed to the next round.

Hopefully this answer cleared things up for you.

**Comment by Koura** [comment]
This issue should now be fixed. Sorry for the inconvenience caused.
