### ISSUE TITLE
Initial application v2 API

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#699]
- [x] return workflow info in application API
- [x] POST /v2/applications/command
- [x] command: submit
- [x] command: approve
- [x] command: reject
- [x] command: close
- [x] command: request-decision
- [x] command: decision
- [x] command: request-comment
- [x] command: comment

**Comment by luontola** [comment]
How should we document the commands?

**Comment by opqdonut** [comment]
maybe `rems.workflow.dynamic` could export a schema for the commands
