### ISSUE TITLE
automatic deployments to vm0773 vm

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#725]
- [x] upload artifacts to circleci
- [x] prototype deploy job under NitorCreations github org
- [x] real deploy job under CSCfi github org
- [x] github hook to start deploy to vm0773

**Comment by Macroz** [comment]
What is the status of this @opqdonut. Did you send email / receive responses?

**Comment by opqdonut** [comment]
the CSCfi/rems-deploy repo is now connected to circle

instead of triggering, let's try scheduled deploys at midnight utc

you can also manually trigger the deploy, of course
