### ISSUE TITLE
REQUEST: local authentication

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#734]
Dear REMS development team,

We are evaluating REMS and according to the test data users can login without a password by clicking on the suername. Would it be possible to have local authentication against username and password?

Is this something that could be developed as a new feature?

thank you very much

**Comment by Macroz** [comment]
Hi!

It's not on our product backlog at the moment. It is definitely possible and not very difficult, but there is quite a lot of work concerning password resets, confirming email addresses etc. auxiliary flows, that would have to be implemented too in a real solution.

If you just mean that can we have a table in the database to authenticate against, then that is much easier and less work, but then all the other concerns would have to be implemented by someone else somewhere else. How would the users be created and managed?

**Comment by Masber** [comment]
Hi @Macroz 
 
apologize for the late response.
 
We have been thinking around your comments and we want to make this as easy as possible. This is what we thought:
 
1.            User login creation page where anyone can register. Each registered user is a default Applicant.
2.            The REMS sysadmin creates an OWNER role.
3.            For each cohort (Workflow) the Owner then can assign registered users to different roles eg. Approver, Reviewer etc.
 
In regards password reset or change requests, we think the REMS sysadmin should do this upon user request by email.
 
Note: REMS sysadmin is just an user with sudo access to the machine running REMS.
 
Could you please let me know if this is possible?
 
thank you very much
 
Manuel

**Comment by Macroz** [comment]
Hi,

It's possible but not in the backlog for this year. We can discuss these features with CSC and see where they would end up in priority.

I see a few difficulties in this such as that admins would know user passwords if they set them. Or there would have to be a reset functionality and password change functionality and all these add up like I mentioned. So there is quite a lot of work that would have to be implemented in a real solution, even if it's simple. I estimate a couple weeks of work because there are many new screens and lots details like emails to send.

**Comment by luontola** [comment]
Would it be plausible for you to use a third-party authentication service? For example [Auth0](https://auth0.com/) would provide integration with many [identity providers](https://auth0.com/docs/identityproviders) (Google, Facebook etc. and also password-based and passwordless authentication), so there is no need to create a custom solution to a generic problem.

**Comment by Masber** [comment]
@luontola yes, that would work, we can ask our users to use their google, facebook, etc account to login.

**Comment by hukka** [comment]
Spring cleaning
