### ISSUE TITLE
Add UI component snapshot testing

### ISSUE THREAD

**Issue by Kauko** [CSCfi/rems#756]
Add snapshot testing á la Jest (using some library). Maybe the example macro could add snapshot tests automatically..?

**Comment by Macroz** [comment]
Also should consider [Gemini](https://github.com/gemini-testing/gemini) or similar for visual snapshot testing.

**Comment by Kauko** [comment]
I tried using juxt/snap, but apparently it doesn't work with doo..? Looks like snap isn't in clojars, so I had to switch to using deps.edn, and then when I required snap.core in a test file, the tests didn't run at all. I then tried to add another test runner which would use the new cljs.test, but I couldn't get the thing working quickly, so I gave up. I'm pretty sold on snapshot testing, but I'm not sure they're valuable enough to warrant all the hoops I had to jump through.

**Comment by Kauko** [comment]
I did another test with opticlj. I got it working, but surprisingly it doesn't seem to work with Reagent components. To run opticlj in cljs test, the compilation target needs to be nodejs, which causes errors with xmlhttp

**Comment by Kauko** [comment]
Final comment - I added opticlj to another project, and while it works there and I finally got it working, it's not a very well implemented library. I'm just going to close this issue, as there's no clear path forward, and if we _really_ want to add snapshot tests at some point, we can just reopen this issue, or open another one.
