### ISSUE TITLE
Support to DUO

### ISSUE THREAD

**Issue by mikael-linden** [CSCfi/rems#776]
Develop support to Data Use Ontology https://github.com/EBISPOT/DUO
Assume resources come with data use descriptions ("patients in this dataset have given consent for non-profit cancer research") and Applicants describe their research purpose in a structured way (instead of freetext), for instance checkboxes ("I apply this dataset for non-profit research", "I apply this dataset for cancer research"). REMS should match the Applicant's research purpose with that of the dataset and prepare a proposal for the Approver.

**Comment by hukka** [comment]
https://www.ga4gh.org/news/data-use-ontology-approved-as-a-ga4gh-technical-standard/ has a friendly intro. This is related to work on ELIXIR-AAI #1319 and other GA4GH tasks.

**Comment by jaakkocsc** [comment]
Here's a user story with some requirements: https://docs.google.com/document/d/100RDtOI-Tp_pr2AYXUi-bZ_w4Lm61ol83_knC26jBWU/edit

**Comment by opqdonut** [comment]
split into multiple tickets in a milestone: https://github.com/CSCfi/rems/milestone/26
