### ISSUE TITLE
vTHL2: simplify db.applications

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#779]
There is need to refactor `db.applications` which has grown and contains less than ideal code that mixes old static and new dynamic models.
- [ ] split dynamic applications out from `db/applications`
- [ ] consolidate `db.applications` tests into integration test file and put unit tests along with code

**Comment by opqdonut** [comment]
this will probably get done with #852. consider closing

**Comment by Macroz** [comment]
I think the first part will not be done because the applications will use the new actions only. The second part is about refactoring the tests after that is done. I'll close this issue.
