### ISSUE TITLE
Form validation warnings disappear after closing the dialog

### ISSUE THREAD

**Issue by Kauko** [CSCfi/rems#786]
![dec-11-2018 14-55-13](https://user-images.githubusercontent.com/804522/49802243-06a00d00-fd55-11e8-9f24-0fc6c121d591.gif)

Not sure if this relates to #669 or #770 

When you try to submit a form with validation errors, the application shows you the errors in dialog window, and highlights  the fields with errors. When you close the window, the validation errors disappear.

**Comment by Kauko** [comment]
I wonder if this relates to the new #768 dynamic workflow?

**Comment by Macroz** [comment]
Fixed in #788
