### ISSUE TITLE
API example for user creation

### ISSUE THREAD

**Issue by Masber** [CSCfi/rems#790]
Dear REMS development team,

We just realised that version 2.4 provides an API to create users into the system. We would like to use it but could not find any example in the documentation.

Would it be possible to have a curl command example to create a user we can use on our test environment?

thank you very much

**Comment by Macroz** [comment]
Hi!

It would be something like this (note you must have owner permissions for the user that creates a user)

```
curl 'https://localhost:3080/api/users/create' -H 'x-rems-user-id: RDowner@funet.fi' -H 'Accept: application/json' -H 'x-rems-api-key: 42' -H 'Content-Type: application/json' --data-binary '{"eppn": "testuser", "mail": "test.user@example.org", "commonName": "Test User"}'
```

**Comment by opqdonut** [comment]
It looks like the swagger-ui version we use only shows the curl command if you click "Try it out".

In any case, the swagger docs should be enough for using the API. If they are missing some info, let's add it.

![rems-user-swagger](https://user-images.githubusercontent.com/207385/50076847-7138c900-01eb-11e9-843f-92bc065aa7ed.png)

**Comment by hukka** [comment]
Spring cleaning
