### ISSUE TITLE
vTHL2: Show who a request was sent to and what they replied

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#811]
NB: Concerns both static and dynamic application events.

Approve and review requests and responses:
- application history must include the information to whom the approval, review or comment request was sent to. We store the actor in userid column in `application_event` table and the receiver in the `eventdata` column where it should be shown from or create a new column for static applications?
- responses must be tied to requests, meaning that on history list it must be unambiguous that which response belongs to which request. 

![See image for design.](https://user-images.githubusercontent.com/823661/50593357-be31c600-0ea0-11e9-9bcd-e6b54aea1e04.png)

**Comment by Macroz** [comment]
![events](https://user-images.githubusercontent.com/823661/50593333-a5291500-0ea0-11e9-82ac-ee208716d506.png)
