### ISSUE TITLE
vTHL4: Implement editor feedback with status modal like in resource editor

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#826]
- [x] resource
- [ ] catalogue item
- [ ] workflow
- [ ] license
- [x] form

Implement status modal to show errors or success before navigation.

Possibly implement also field validation that shows correctly for all.

**Comment by opqdonut** [comment]
related: #1362

**Comment by opqdonut** [comment]
The UX of the remaining editors is good enough. See also #1469
