### ISSUE TITLE
vTHL2: Dynamic workflow additional license request

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#830]
The handler should be able to request a new license to be approved. I.e. create an agreement that is then signed by accepting the license. Old REMS abuses licenses for this. We could instead have a license request that the receiver must approve just like the other actions of the dynamic application. The request form can have a shortcut into creating a new license.

- [x] license request (new licenses visible, explicit approve licenses button)

**Comment by Kauko** [comment]
#653 should maybe be done first?

**Comment by hukka** [comment]
Also the question in #914 should be discussed first

**Comment by Macroz** [comment]
At the moment creation of a new license is not possible from the handler. This is because now we have that right only for the owners, not for the handlers. I think it's useful at this point to ask the users if handlers and owners are the same or different group of users or should we expose (some of) the admin pages to handlers as well.
