### ISSUE TITLE
vTHL3: Preview form

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#835]
When creating or editing a form, there should be a possibility to preview what it looks like to the applicant. This could open a new window, modal or show beside the editor on large screens.

- [x] preview action while creating a new form #1110 
- ~preview action while editing an existing form~ no form editing is planned
- [x] preview for existing form #1113 
- [x] style adjustments: editor and preview side-by-side

The form does not need to be functioning but it should look like what it will look like in a real application.

Plan of attack:
- [x] push current form creation model as is into db (still keeping old save functionality)
- [x] make an API for returning that model
- [x] UI preview with that model
- leftover refactoring opportunities in #913

**Comment by opqdonut** [comment]
`/forms/v2/:id` returns the new form template
