### ISSUE TITLE
vTHL4: Bulk change form of catalogue items

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#837]
Apply a new form to a set of catalogue items. REMS1 creates new catalogue items under the hood and disabled the old ones. In applications that are already in processing the old form is still used because they still use the old catalogue item.

List view should be done before this issue.

- [x] select multiple catalogue items (by clicking checkboxes next to the items)
- [x] select bulk operation (change form)
- [x] form with options for selectable form (autocomplete?)
- ~check if catalogue item name should be possibly updated here too (e.g. to add version or year number)~ decided not to do this yet
- [x] create new catalogue items for each catalogue item with the new form
- [x] disable & archive the old catalogue items
- ~link the new catalogue item to the old to track~ decided not to do this yet

**Comment by jaakkocsc** [comment]
See #1763
