### ISSUE TITLE
vTHL3: Show last event time for applications

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#843]
At the moment there is no visibility to the applicant if something is happening to their application. Something like "latest activity" needed.

- [x] in the status area, always show a "last event" time that includes any possibly hidden events
- [x] make sure no details of events are sent to the applicant that should not be seen (could either calculate on serve or send all event times even and withholding any other details)

**Comment by Macroz** [comment]
Maybe show the latest event dates even for hidden events?

**Comment by hukka** [comment]
I added `:latest-modified` to application data, which includes also modifications from hidden events.
