### ISSUE TITLE
vTHL4: Free commenting for dynamic workflow applications

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#845]
THL wants sometimes to add comments to application that are not visible to applicant. They are wishing a checkbox or similar if the comment can be used to the applicant.

Internal comment: everyone in THL can see who is a handler, or who is part of the handling (i.e. commenter, decider)
General comment: also applicant can see

- [ ] new action to leave a free comment
- [ ] possibility of selecting if the comment is internal or public (internal being default)
- [ ] test that the applicant doesn't get the comment data from API for private comments
- [ ] test that unrelated users don't get anything for the application

**Comment by hukka** [comment]
If these would be different event types, it would be trivial to implement the hiding in `api.applications/hide-sensitive-events` and `hide-sensitive-dynamic-events`

**Comment by hukka** [comment]
This is separate from current commenting functionality. This is related to non-dynamic roles only, does not thread and is not related to comment requests.
Some roles (handler for now) can leave comment events, that are either visible or not to the applicant.

**Comment by luontola** [comment]
Support for non-requested comments (i.e. make request-id optional) would also solve this kludge: https://github.com/CSCfi/rems/blob/ec6dac0/src/clj/rems/migrations/convert_to_dynamic_applications.clj#L77-L78
