### ISSUE TITLE
Naming things

### ISSUE THREAD

**Issue by luontola** [CSCfi/rems#853]
Go through the core concepts in REMS and figure out how to name them. For example the meaning of "application" is overloaded when the get application API returns an application which has an application field.

**Comment by opqdonut** [comment]
Some suggestions:

- form template: the set of fields that a user needs to fill to apply for a given resource
- form: the field values that the user filled
- application: the entirety of an application: applicant+form+resources+events+state

**Comment by luontola** [comment]
Some more suggestions:

- application: the whole lifecycle of applying for a resource
- form: a filled in form template, possibly multiple draft forms and submitted forms per application
- form template: a set of empty fields
- field: previously called "form item"

Also the name "catalogue item" is clunky: the catalogue UI calls them resources, so maybe we should them the same way in code and rename resource to something else.

**Comment by Macroz** [comment]
UI terminology is somewhat dependent on the user terminology i.e. LBR wants kielivara. I think it's possible to remove the resource from catalogue and use item there instead but still you are picking the resources you want to apply for so resource is just as valid there.

**Comment by Macroz** [comment]
I don't like renaming form to form template. Form, resource and workflow are core concepts. Lets rather have (form) answers or something instead for the application.

**Comment by Macroz** [comment]
`resid` in the `resource` table should be named something else because `resid` is used to refer to the id of the resource which is our internal id and not the external id. Maybe `extid`?

**Comment by luontola** [comment]
There is a need for a common term to use about the handlers, commenters and deciders. After removing the round-based workflow, the word "reviewer" should be available for use. Got any better suggestions?

The word "actions" is currently overloaded. There is the actions page, but also the buttons in the application page are called actions. One suggestion is to rename the actions page to review page, where the reviewers will go through the review process of an application.

**Comment by luontola** [comment]
The legacy data model (inherited from REMS1) uses the word "item" in lots of places, typically when one thing contains many things, instead of inventing a descriptive term for it. There are form items (i.e. fields), catalogue items, application items (no idea what it is) and at places the application itself is also called an item. Item is a similar empty word to "object", "data", "manager" etc. and should be replaced with a term in the users' domain. 

The hardest of these to name seems to be catalogue item. A mail-order catalogue contains mail-orderable products, a photo catalogue contains photos... an item catalogue contains catalogue items? 😕

In the UI when there is a "resources" column, it doesn't actually say the name of the resource, because in the legacy data model resources don't have a name, only an ID, so actually the resources column says the name of the catalogue item. This hints that maybe catalogue items should be called resources. 

On the other hand, catalogue item links the resource together with a workflow and form, which doesn't seem something a resource should know about, so maybe parts of catalogue item belong to resource and additionally there is some further concept bound to it.

When an application is created, the catalogue item is used to decide which workflow and form to use when applying for a resource. The fields of a catalogue item are exploded into the application created event (the catalogue item ID is kept around only for getting the resource name from the legacy data model). In this sense the catalogue item serves as a template for creating an application.

Maybe one way to help think about the naming is to first choose as concrete words as possible; instead of generalizations like "resource", call it "corpus". After there are concrete terms for every concept, we can think about domain-independent terms.

**Comment by luontola** [comment]
Further indication that the catalogue items should be called resources: the example theme calls them (language) resources.

![admin pages](https://user-images.githubusercontent.com/42678/53162961-c4f1d500-35d5-11e9-862d-a30ebb43655b.png)

**Comment by opqdonut** [comment]
I tried to describe the current glossary on #1007
