### ISSUE TITLE
vTHL2: Theme deployment

### ISSUE THREAD

**Issue by cscwooller** [CSCfi/rems#857]
https://remsdev.kaj.pouta.csc.fi/ is currently down cause there is no folder theme-thl on the server. Bundle theme(s) somehow to installation.

also, move theme-thl and theme-lbr to the rems-deploy repository

**Comment by opqdonut** [comment]
#860 is for this

**Comment by opqdonut** [comment]
I tested it, worked for me.

**Comment by opqdonut** [comment]
Let's close this and reopen if problems persist.
