### ISSUE TITLE
vTHL3: Performance testing

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#863]
Check performance of static and dynamic applications in the new version.
- [x] check performance of especially actions page with some hundreds of applications closed and a few thousand archived.
- [x] check that the catalogue page can handle a thousand catalogue items
- [x] populate enough rows in test data so regular dev use hits the potential limits too
- [x] investigate how much data there is in production, how much new data is expected per year, and whether it all can be held in memory at once
- [x] consider whether `rems.api.applications-v2/all-applications-view` should be cached and built incrementally
  - the spike code which was removed in https://github.com/CSCfi/rems/pull/878/commits/2b85f467b1589b669cc3da9acec9f851288fc182 can serve as a base
  - even just memoizing the injections should improve the performance much
- [x] consider whether `rems.db.dynamic-roles/get-roles` should be cached and built incrementally

**Comment by hukka** [comment]
Are we interested in basic web KPI like first paint and time to interactive, i.e. running lighthouse? Do we have any targets, other than "it is not unusable"?

In any case we would need some way to track performance, so that we can see if we would get better or worse.

**Comment by Macroz** [comment]
History: the production installations have a lot more data than test dataset so there have been too slow page loads.

I think a suitable sweet spot could be a browser test to see that the initial page load and render is "instant" (< 100 ms) and the long content (lists) that is loading (i.e. with a spinner) should have been rendered soon after (< 1 second). Opening the archived / handled applications can take a bit longer. 

Sorting columns is also surprisingly slow but there is a separate issue for that.

Perhaps this could be a test fail or if it creates a lot of false positives because of variance then it'd be interesting to plot the times somehow so we see that the trend is not bad.

**Comment by luontola** [comment]
Initial tests on a development machine with a production database dump with about 1000 applications gave the following results:

Every request (even `/api/config`) takes at least 1.2s because `rems.db.dynamic-roles/get-roles` loads all events on every request without caching.

Loading the actions page takes 30s. This is probably due to the lack of batching for dynamic applications.

**Comment by luontola** [comment]
Now that the v2 APIs are in use, the actions page loads slightly faster, in about 10 seconds. Catalogue and applications pages also take as long to load, since they all are based on the same code for listing all applications.

**Comment by mmatthiesencsc** [comment]
In the pre-production LBR3 instance this translates to 15 secs loading time. Too long. I suggest to only load the most recent applications and give a "show more" option. Especially the Catalogue page should not load applications? If you have to make trade offs prioritize pages that are customer facing (like Catalogue), where customers often are behind slower lines.

**Comment by luontola** [comment]
It's being optimized in #1106. It should be easy to get page loads under 100ms.

**Comment by mmatthiesencsc** [comment]
Ok, good to know!
