### ISSUE TITLE
vTHL4: Update form

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#865]
Admin should be able to update a form.

Implement copying first. See #836 

- [ ] update action
- [ ] modifies old if there are no uses of the form yet or makes a copy of the form and disables to old one if the old one is in use already
- [ ] allow updating of information
- [ ] show in list view in #805

**Comment by opqdonut** [comment]
it makes sense to solve #913 first

**Comment by opqdonut** [comment]
enough of #913 is done for work on this to start
