### ISSUE TITLE
vTHL4: Bulk change workflow of catalogue items

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#871]
Apply a new workflow to a set of catalogue items. REMS1 creates new catalogue items under the hood and disabled the old ones. In applications that are already in processing the old form is still used because they still use the old catalogue item.

See #837 and perhaps combine into one bulk change.

**Comment by opqdonut** [comment]
Waiting for a real use case. This is easy to do via SQL if needed only rarely.
