### ISSUE TITLE
vTHL4: Full text search

### ISSUE THREAD

**Issue by Macroz** [CSCfi/rems#873]
Improve the search functionality by offering a full text search based on all information in an application. One search field. This possibly replaces the column based filters or they should be improved to suit the improved functionality (create new tasks if need updating and not just removal).

- [x] search from all content of the application
- [x] one search field
- [x] try implementing full content search within backend first
- [ ] ~~search handled applications checkbox~~

**Comment by hukka** [comment]
Closed by #1000

**Comment by Macroz** [comment]
Reopening. Still missing MVP of searching from all the application fields.

**Comment by luontola** [comment]
Could application fields using in-memory Lucene index: http://lucene.apache.org/core/8_0_0/memory/org/apache/lucene/index/memory/MemoryIndex.html
