### ISSUE TITLE
Store forms as JSON documents instead of relations

### ISSUE THREAD

**Issue by opqdonut** [CSCfi/rems#913]
(moved leftovers here from #835)

Current status:
- when a form is created, it's stored in the db both as a document (`form_template`) and as relations (`application_form`, `application_form_item`, `application_form_item_map`)
  - this is the document the _write model_
- there is an API for fetching the write model document (`/api/forms/:id`)
- there is an alternate document format that is returned by the new application api (schema `rems.api.schema/Form`)
  - this is the document _read model_
  - the read model is used by the application rendering code on the frontend
- when creating or viewing a form, the write model is converted to the read model to render a preview

To do:

- [x] unify read and write models (probably by using the read model for writing):
  - [x] store the read model in `form_template`
  - [x] get rid of read-to-write-model conversion in preview
- [x] read `form_template` instead of `application_form_*` in application api implementation

**Comment by opqdonut** [comment]
after #1299, the `application_form_*` tables are no longer used by the application workflow code

**Comment by opqdonut** [comment]
the last remaining user of the `application_form_*` tables is `rems.db.applications.legacy`

**Comment by opqdonut** [comment]
I think this has progressed far enough now to unblock #865

**Comment by luontola** [comment]
Removing old db tables and related source code has been moved to be part of #1101.
