### ISSUE TITLE
Project plan element location

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#958]
If project plan for an application is provided as an attachment, it shows on the screen partially on top of another element.

<img width="729" alt="screen shot 2019-02-22 at 9 22 03" src="https://user-images.githubusercontent.com/45791943/53226435-a9dd9e80-3683-11e9-98db-6b2afb0e98b4.png">

**Comment by Macroz** [comment]
What is partially on top of something? Do you mean the button is uncomfortable close to the text?

**Comment by foxlynx** [comment]
Yes. project_plan.txt link button is too close to "Project plan (optional)" label.
