### ISSUE TITLE
vTHL4: Application or decision autosave

### ISSUE THREAD

**Issue by foxlynx** [CSCfi/rems#979]
It is now an existing problem that sometimes application or decision is lost because the session expires (REMS1). Autosave could tackle this problem.

Easier to implement for application, decision autosave creates some weird middle state where application would have comments by approver but the application would not yet be approved.

**Comment by hukka** [comment]
Also any kind of edit should immediately make a ping to the backend to verify that session is still alive. Otherwise autosave would still fail if there's significant time between opening and editing an application.

**Comment by foxlynx** [comment]
This might be a problem only in REMS1, REMS2 does not have this cause it does not run on Liferay.

**Comment by luontola** [comment]
To find out how much of an issue this is, we could grep the production logs for `/api/applications/save-draft` and count that how many of them returned HTTP 401 or 403.

**Comment by opqdonut** [comment]
Let's do #1525 now and add autosave later if needed.
